label coolguyyes:
    mc "(I'd rather not do this, but I want to thank him for saving my life. Plus, I do need a home to return to if I want to live well."
    mc "I'll join."
    "Cool Man" "Excellent, just as I expected. Pack your things, I'll see you around shortly."
    mc "(He stands up and steps out of the room, his dress shoes clicking with every step.)"
    mc "(As I get up from the bed, I feel slightly uncomfortable.)"
    mc "(I haven't gotten up in a while.)"
    mc "(I'm probably out of shape too.)"
    mc "(I sigh as I gather my clothes in one place.)"
    mc "(But before I can put them into my bag, I feel my vision begin to fade.)"
    mc "(Not again…)"
    with fade
    mc "(My eyelids feel uncomfortably heavy.)"
    mc "(My body feels compressed as if I've shrunk by multiple inches. But I can that I'm on a bed of some sort.)"
    mc "(My eyes feel dry, despite having been covered for as long as I have slept.)"
    mc "(I slowly open my eyes. The room I'm in is foreign, but it looks somewhat homely. The ceiling is such a light brown color that I feel like it's white and my eyes are tricking me.)"
    mc "(I blink a couple of times to try to wet my eyes before giving up as it seems to have no effect.)"
    mc "(I get out of my resting position and look around the room. I'm wearing a light set of pajamas. There's a cup of water on the nightstand, with a small note next to it.)"
    "Nurse" "Good morning, [name], I hope you had a good rest. Your work clothes are in the closet, enjoy your new home."
    mc "…"
    mc "(I get out of bed and walk over to the closet. It's not the largest closet, but it has a mirror next to it so I can check my hair.)"
    mc "(These pajamas are pretty cute, aren't they.)"
    mc "(Wait, these are different from the ones in the hospital.)"
    mc "(Did he…)"
    mc "(Why?)"
    mc "(I decide to not dwell on it for too long, since I doubt he did much more than swap my outer clothes. I sure hope he didn't, anyway.)"
    mc "(Inside the closet is a clean, black and white formal outfit. It's about the most plain yet decorated outfit I've seen.)"
    mc "(I step outside of the bedroom, expecting a hallway, only to encounter the living room.)"
    mc "(Not exactly the largest apartment I've got here.)"
    mc "(But a home is a home. There's a small TV with an armchair in the room, so it's not the worst.)"
    mc "(On the other side of the room is an opening into the kitchen. I can't cook though, so I hope that guy got me some food.)"
    mc "(I open the fridge and look around. Nothing.)"
    mc "(My expectations were low, but I still feel like I've been scammed.)"
    mc "(I sigh and shut the fridge door, hoping that my past self magically remembers how to make breakfast.)"
    mc "(But before I accidentally start a fire in my brand new home, I spot a plate of eggs and a glass of milk. And another note.)"
    mc "Eat up! (There's also an image of a thumbs-up.)"
    mc "(I'm sorry for ever doubting you, cool guy.)"
    mc "(I quickly eat up the eggs and down the milk. It doesn't taste that bad. Who am I kidding, it's the best meal I can remember. Anything beats IV drip.)"
    mc "(I head for the door before I realize that I don't know where work is.)"
    mc "(That isn't that much of a problem though, since that guy probably left another note.)"
    mc "(There isn't one though. He only left the house keys and a map with a small red circle on a building.)"
    mc "(I guess he ran out of time…)"
    mc "(I step out of the door and lock it behind me.)"
    mc "(Now that I'm out of my house, I suddenly don't feel like working anymore.)"
    mc "(I don't want to back out now. Not after I've gotten a free home and breakfast.)"
    mc "(I head down the stairs so I can reach the ground level. It's only 2 sets of stairs. I pity those who live on the upper floors, but at least they'll never skip leg day.)"
    mc "(I look at the apartment keys as I'm descending. 308. Not a bad number. It's an even number, at least.)"
    mc "(The workplace isn't that far from the apartment, so I'll just walk there. I should get some exercise, anyway.)"
    mc "(I haven't been outside in a while. The hospital staff never let me leave the premises since I wasn't fully recovered, but I got to walk around the hallways and look out the windows.)"
    mc "(The only thing I could see was trees, though. Large rectangles of green, occasionally intersected by buildings. They got boring after a while.)"
    mc "(They look much more different up close though.)"
    mc "(They're much bigger than I thought. I guess only seeing something from 10 floors up messes with your perception.)"
    mc "(Who would've guessed that life is much more fun when you're not stuck in a hospital room.)"
    jump day1work

label coolguyno:
    mc "(I'm not gonna place myself in danger just so I can buy a home. No matter how nice that apartment is, it's not worth my life." 
    mc "I refuse."
    mc "(He gives me a strange look like he wasn't expecting that.)"
    mc "Sorry, but I don't want to put myself in danger."
    "Cool Guy" "No matter. Suit yourself."
    mc "(He tosses me a folded map of the city with a red trail, showing the route to the apartment complex from the hospital.)"
    mc "I said I didn't want to join."
    "Cool Guy" "Not like you have a choice, do you? I don't think a broke amnesiac will survive long on their own without a place to call home. Plus, the major players at the DEU want to see their money well spent."
    "Cool Guy" "Room 308. I left a few furnishings so you don't have to sleep on the ground."
    mc "(He places the key on top of the map and leaves. The clicks of his dress shoes echo down the hallway as he leaves the door open.)"
    mc "(I slide out of bed and stack my spare clothes with the map and keys. It's not much, but it's better than only having one set.)"
    mc "(I place them all into a small plastic grocery bag and slide the keys into my pockets.)"
    mc "(As I unfold the map, a small slip of paper falls out. It's a handwritten note, seemingly meant to convey some important information.)"
    mc "(What's this?)"
    "Note" "Report to DEEZ Corp tomorrow for your first day at work. Dress well."
    mc "(That bastard…)"
    mc "(I said I didn't want to join. How pushy can one be?)"
    mc "(I want to get angry at him, but whenever I remember his beautiful face I just can't get mad.)"
    mc "(I decided that the best way to get back at him was to not think about him at all, so that way he doesn't even get to be in my mind.)"
    mc "(Before I step out of the hospital room, I turn around to take a good look at what I called home up until now.)"
    mc "(Now that I see it from here, it looks incredibly plain. The walls and ceiling are a light beige color, while the floor is a strange tiled pattern that connects with the hallway.)"
    mc "(And the white curtains that I rarely move look like they've been taken straight out of a fabric store.)"
    mc "(Strangely enough, I feel nostalgic. This cookie-cutter room that could be put anywhere and still called a \"hospital room\" makes me feel at home.)"
    mc "(Not a single part of it is unique. None of it stands out, and I would confuse it with the room next to mine if they were mixed around.)"
    mc "(But I just can't leave it behind. I've called this place home for years, and now I have to leave it? I don't want that.)"
    mc "(I want to stay in the lands of familiarity, keeping change at bay for the rest of my life.)"
    mc "(But I must move on. I can't stay like this forever.)"
    mc "(I feel weird being so emotional about a hospital room. I'm almost crying about something that most people wouldn't even bat an eyelash at.)"
    mc "(But these emotions are very much real. I can't fault myself for feeling them, can I.)"
    mc "(I finally tear myself away from the door and shut it behind me.)"
    mc "(It's time to move forward.)"
    mc "(I walk towards the elevators, clutching my bag of clothes tightly against my chest.)"
    mc "(It's all I have, after all.)"
    mc "(When I step out of the hospital, a golden ray of sunlight hits me in the eye.)"
    mc "(Damn, that's bright.)"
    mc "(I'm not used to the sunlight. The nurses always kept the curtains shut because it could bother the patients.)"
    mc "(I pull the map out of my pocket and unfold it so I can tell where I should be heading.)"
    mc "(It's quite the walk away. At least my legs will get some well-needed exercise.)"
    mc "(The distance isn't the shortest, but the route itself is pretty simple.)"
    mc "(I study the map one last time before I fold it back up and put it into my pocket.)"
    mc "(The outside world is quite incredible. The trees, the air, the sky. All of it feels refreshing compared to the insides of the hospital.)"
    mc "(Did the previous me get to experience this all the time? Lucky…)"
    mc "(The sounds of cars rushing by me are also quite refreshing. All different makes and models, with a few of them nearly identical save for the color. They make a nice sound, speeding by at such speeds that they appear as a blur to me.)"
    with fade
    mc "(By the time the building comes into view, the sky has already become a melancholy mix of pink and gold.)"
    mc "(The apartment complex looks pretty simple. A medium-sized parking lot right in front of a tall, 5-story building of apartment after apartment.)"
    mc "(As I'm about to walk up the stairs, a young man rushes down the stairs, bumping into my shoulder.)"
    show joejoe
    "Young Man" "My bad."
    mc "Sorry."
    hide joejoe
    mc "(He rushes off before I can get a good look at his face.)"
    mc "(That guy seems like he's in a hurry. I wonder what he's up to.)"
    mc "(I climb up the rest of the stairs with no interruptions and reach the third floor.)"
    mc "(Room 308, room 308.)"
    mc "(Right here.)"
    mc "(The lock clicks open and the door swings back with a slight squeak.)"
    mc "(Not bad.)"
    mc "(The first thing I notice is the light aroma of mint, pouring out of a small wall-connected air freshener. It instantly gives me the impression that the apartment is cleaner, despite doing nothing to the actual appearance of it.)"
    mc "(The main room has a small TV with an armchair, along with an empty bookshelf.)"
    mc "(There's an opening to the kitchen and another to the bedroom.)"
    mc "(I head to the bedroom first to put away my clothes.)"
    mc "(The closet is nearly empty, besides a few clothing hangers and a set of business clothes off to the side.)"
    mc "(He was serious about me going to work…)"
    mc "(I put my clothes on the hangers and put them all into the closet.)"
    mc "(I'd like to check out the kitchen, but honestly I'm too tired. I'll clock out for the day right now.)"
    mc "(I toss my current clothes into the laundry hamper and put on my pajamas before I slide into bed.)"
    mc "(While I'm here, I should get a general map of the whole apartment in my head. I doubt it'll help with anything, but it makes me feel like I've been here longer than I have.)"
    mc "(My mind wanders around the countless thoughts that have come to fruition, from the cool man to the streets outside. After a while, I sifted out the meaningless ones and presented the major events to the imaginary court inside of my head.)"
    mc "(First, I now have a home and a job. That solves my two major issues. What do I even do for my job though? I don't think that guy left any instructions for me. I can't even work, then.)"
    mc "(I don't think that matters though since everyone around me will lower their expectations accordingly. No matter how well I do it'll always be as expected.)"
    mc "(There is more on my mind than just that, but I don't care enough to handle that.)"
    mc "(I can't sleep, though. I open up my eyes as if that might help. Maybe it'd reset my sleep, or make me more tired so I can rest.)"
    mc "(Right above me is the same darkened ceiling that I've seen every night in the hospital. With the light off, it's hard to tell where the ceiling ends and the walls begin, but it's easier when I look directly upwards.)"
    mc "(It doesn't matter if my eyes are closed or open, it's still just as dark. But I close my eyes anyway, and lean to the side.)"
    mc "(I slowly drift off into sleep…)"
    with fade
    mc "(My mind feels hazy like I haven't fully woken up yet. I can tell that I'm at least somewhat awake, but I don't want to move.)"
    mc "(I lie in bed for another 10 minutes before I feel like I've fully woken up.)"
    mc "(Now that my mind is clear, I can think about what I want to do for the day.)"
    mc "(I might as well head to work. I don't have anything else to do.)"
    mc "(Even though I don't want to.)"
    mc "(I get out of bed and run my fingers through my hair, brushing it away from my eyes.)"
    mc "(I stretch out my arms as far as they are willing to go before doing the same to my legs.)"
    mc "(Finally, I exhale deeply and open up my closet to get dressed.)"
    mc "(I put on my business clothes and head to the kitchen for breakfast. There's a plate of scrambled eggs and a glass of milk on the counter. I guess the cool guy made it for me.)"
    mc "(It tastes pretty good. I'd be fine eating this every day, but it'd probably get boring soon enough. I finish the plate in just a few minutes. It's time to head to work now.)"
    mc "(I head out the door and lock it behind me, before going down the stairs to the ground level.)"
    mc "(As I look at the map again, it doesn't seem that far. I should be able to just walk there.)"
    with fade
    jump day1work