label day1work:
    mc "(The building is in sight now. That only took around 20 minutes, I think.)"
    "The MC is outside of the DEEZ Corp building."
    mc "(What a tall building. It's the tallest one on the block.)"
    mc "(No one's walking into the building. I'm getting a bit nervous.)"
    mc "(Am I in the right place? I check the map again, certain that I read it wrong, yet every street marker and building tells me that I'm at the correct location.)"
    mc "(I should be more confident. No one would walk into an office building if they don't work there, right? I'm one of the few people who has the right to go in.)"
    mc "(I adjust my already correctly adjusted tie and step through the automatic doors.)"
    mc "(My face is hit by a light sweep of air conditioning. It's a comfortable feeling for an office building, but it's already cold outside.)"
    mc "(Right in front of the entrance is a medium-sized desk. There's a woman sitting at the desk, typing on her computer.)"
    mc "(Even though she's looking down, I can tell that she's beautiful. Both her clothes and her hair are very finely kept.)"
    mc "(I adjust my tie again and walk up to the front desk.)"
    mc "H-Hello."
    "The woman at the desk" "..."
    mc "(Did she hear me?)"
    mc "(I sit in silence while the woman types on her computer for a few more seconds.)"
    mc "(She finally looks up at me, but she looks back to her screen.)"
    mc "(Wow, she's even prettier close up. Her eyes are nice. At least a 10, maybe even an 11.)"
    mc "(After a few more seconds, she stops typing and leans back to look at me.)"
    show sigma
    "Woman" "How may I help you?"
    mc "I recently got hired to work here. "
    "Woman" "Mhm."
    mc "(She carefully studies my clothes, as if she's scanning for every single imperfection in my outfit.)"
    mc "(I think I see the slightest bit of a frown appear on her face, but it's so slight that I can't tell if I was just seeing things.)"
    mc "(Her antennae twitch before she finally breaks the silence.)"
    "Woman" "Welcome to the company. I'm Sigma."
    s "I'll give you a tour."
    mc "(She gets up from her chair and walks around the desk area.)"
    s "Follow me."
    mc "(She turns around on her heels and walks away at a rapid pace.)"
    mc "(I have to run to catch up with her.)"
    with fade
    s "If you're the same [name] as the files tell me, you're working as a Charitable Urgency Manager. If there's a disease that someone needs handling, it's your job to suit their needs and help them."
    s "Work starts at 9 am sharp every weekday, but sometimes you might get called in on the weekends."
    s "You don't need to follow the dress code every day, by the way. I would like it if you wore a suit every day, but the quality managers only check once a month."
    with fade
    mc "(Finally, Sigma pauses in front of a department layered with cubicles.)"
    s "Charitable Urgency Managers are grouped in with the Disease Management section. Most of these guys deal with the paperwork though. You should probably make as many friends with them as possible."
    mc "(She walks around the lines of cubicles until she finds one without a name labeled on the chair.)"
    s "This one will be yours. You can put your personal belongings underneath your desk, but be careful not to let them move outside of your designated area."
    mc "(Sigma starts to walk away before she suddenly stops.)" # do some transition stuff here? either fade her out for a sec or have her move out and move back
    s "Oh, I forgot to mention. You'll get an hour break at 12 for lunch and other stuff, but you can also take a 5-minute break whenever you want. You only get two per workday, though. Don't waste them."
    mc "(Sigma gestures for me to follow her before she walks toward the back of the department.)"
    scene bg cooler
    with fade

    s "Here is the broken corner."
    hide sigma
    mc "(There's a small coffee machine on the desk and a water cooler right next to it.)"
    mc "(I reach for a paper cup, but I suddenly bump into another person doing the same thing.)"
    show joejoe
    mc "Oh, sorry."
    "Other guy" "Sorry."
    hide joejoe
    mc "(I let him take the cup first since he was there first.)"
    mc "(But he does the same thing, for some reason. I'll accept his act of kindness.)"
    mc "(I reach for the cup again, but he does the same. Our hands bump into each other.)"
    mc "(I look up at this strange man who mirrors my every action.)"
    show joejoe
    mc "(Have I seen this guy before?)"
    mc "(Wasn't he one of the people I passed on the way here? Or was he the guy back at the cubicle?)"
    "Incredibly average man" "I'll go ahead."
    mc "(He grabs a paper cup while I'm trying to remember who he is, and fills it up silently.)"
    show sigma at left
    s "That's Joe Joe, one of your co-workers. I honestly can't remember when he got here, or what he does, but he frequents the water cooler every break."
    mc "(Joe Joe downs his water cup in a single gulp. He looks satisfied with his amount of water, even though I could probably hold more in my bare hands.)"
    j "Nice to meet you."
    j "Sorry about those water cooler shenanigans. I'm not the best at interacting with other people."
    mc "(Sigma walks away without a sound, leaving me to deal with someone I've just met.)"
    mc "(He sips the cup again, only taking in the few remaining droplets.)"
    j "I see you've already met Sigma. She's a hard worker, that woman."
    mc "(He laughs quietly before filling up his cup again.)"
    j "I assume you're new to this place. What's your name?"
    mc "I'm [name]. Nice to meet you."
    j "Nice to meet you too. If you're confused about something, you can just ask me about it."
    menu: 
        "What do you do here?":
            mc "(His face shows a hint of surprise before he smiles again.)"
            j "Oh, this will sound kinda bad, but..."
            j "I'm not sure."
            mc "Huh?"
            j "No, I mean, like, I come here every day, right?"
            j "And every day Sigma allows me in without a hitch."
            j "But I don’t do anything for the company. I just wander around for the entire day. Sometimes I help someone with paperwork or run errands for them, but I’m not paid to do that."
            j "I work for the company, but I don't {i}work{/i} for the company. Y'know what I'm saying?"
            j "Oh, I do go get lunch with the crew every once in a while."
            mc "...I see."
            mc "(Why is he even getting paid?"
        "What do I do here?":
            j "I don't know. Did Sigma tell you your position or anything?"
            mc "Yeah, she said I was a Cherishable Undergraduate Major or something like that."
            mc "(His face lights up like a candle once I say that.)"
            j "Ah, yes, the Charitable Urgency Managers. I always loved that title."
            j "I believe you're the ones who handle the diseases. Like, fighting them and whatnot."
            j "But that doesn't happen that often, so I think you just spend most of your time doing paperwork."
            mc "That sounds like a pain."
            j "Yeah, it does."
        "I'm good.":
            j "Glad I could... help?"
            mc "(He looks a bit crestfallen that I didn't ask anything. I feel bad for him now."
    j "Anyways, welcome to the company. I look forward to working with you. I’ll be your water cooler buddy too, I guess."
    menu:
        "Sure.":
            mc "(He nods and waves at me as he walks away.)"
        "No thanks.":
            mc "(He gives me a thumbs up and walks away.)"
    mc "(Now I'm alone at the water cooler.)"
    mc "(I should probably do work now.)"
    with fade 
    mc "(I depart from the break corner and head towards the cubicle that Sigma assigned to me.)"
    mc "(Everybody in this cubicle group is working on something. I sit down as quietly as I can to not bother them.)"
    mc "(No one's around this area except for a single man in the cubicle in front of mine. I guess the other Charitable Urgency Managers are on break or something.)"
    mc "(There's a stack of papers on my desk. It's quite a bit of paper, but it doesn't seem like it would be that difficult.)"
    mc "(I look through the papers to see what I have to do, but they're all completely blank.)"
    mc "(Name, Date of Birth, Disease. They're all important information, but I don't have any information to put in the form.)"
    mc "(I shift around the papers to try to find anything that can help me, but they're forms.)"
    mc "(I keep looking around the papers to see if I had just missed one. Nothing. I check underneath my desk to see if I dropped one. Nothing.)"
    mc "(What do I do...)"
    menu:
        "Ask a coworker":
            mc "(I stand up from my chair so I can see the cubicle in front of me.)"
            mc "(He looks like he's hard at work. Maybe I shouldn't bother him…)"
            mc "(But I have no choice. I don't want to sit here for another 3 hours without anything to do.)"
            mc "Hey."
            mc "(I don't think he heard me.)"
            mc "Hey, you."
            mc "(He looks up from his papers.)"
            mc "(His face reminds me of Joe Joe.)"
            mc "(He has the same brown hair and light blue shirt. The same dark blue pants. He even has a cup of water next to him.)"
            mc "(Wait…)"
            j "Oh, hey [name]! What's up?"
            mc "Oh, it's you."
            mc "Uh, I was wondering, what am I supposed to do for this?"
            mc "(I show him a paper from my stack. He glances over it, then turns it around.)"
            j "Oh for these, you need to get files from the archive. Do you see how each sheet has an ID on it? That corresponds with their file number."
            mc "Thanks."
            j "No problem. The file archive should be right outside the department. You should be able to see the files through the windows."
            mc "(I try to scoop up the stack of papers before realizing I can just write down the ID numbers.)"
            mc "(After that, I head towards the archive room to grab some files.)"
            mc "(All of the people I need to document have ID numbers in the 10000s. I don't think I'll get through all of them though, so I only take the first 10 I need.)"
            mc "(I head back to my cubicle and begin filling out the forms for each and every person.)"
            with fade
            mc "(It takes a lot longer than I expected. I didn't know just how much information we had to record on these people.)"
            mc "(And to think that there are at least 10,000 different files…)"
            mc "(By the time I finish the 9th file, it's already dark outside, and my shift is over.)"
            mc "(I yawn as I get up from my desk. This job isn't difficult, but it sure is a lot of work.)"
            mc "(I need to return these files to the archive room, and then I can leave.)"
            mc "(After I do that, I head for the main lobby.)"
            mc "(When I pass the front desk, I can see that Sigma is still working hard. I guess she ends her shift later, or maybe she just likes working.)"
            s "{size=-10}Fuck this shit. This fucking sucks so bad.{/size}"
            mc "(Yeah, her shift probably ends later.)"
            mc "(I'd rather not bother her while she's working.)"
            mc "(I leave the building and head home.)"
        "Ask Sigma":
            mc "(I get up from my desk and start heading for the front desk. The office building is quite large, but there are markings on the ground leading toward the main lobby.)"
            mc "(As I walk to the front desk, I take a glance at the other departments on the way. They all look identical, except for a few extra storage rooms in some of them.)"
            mc "(I finally reach the front desk.)"
            mc "(Am I even allowed to go behind the front desk? I know I'm technically an employee but it still feels wrong to be there. Sigma might think I'm weird if I do that. But she also might think I'm weird if I talk to her across the desk like a guest.)"
            mc "(I end up deciding to head behind the desk to talk to her.)"
            mc "(She's working hard. Her hands move at light speed, filling out form after form and stacking each paper on top of the other in a neat stack. Based on the number of papers next to her, she has been doing this non-stop for a while.)"
            mc "(I gently knock on the entryway to notify her of my presence.)"
            mc "Sigma."
            s "Yeah."
            mc "I have a question."
            s "Yeah."
            mc "(She doesn't even bother looking up.)"
            mc "I was wondering, how do I fill out the paperwork?"
            mc "(She pauses for a moment.)"
            s "You just... fill it out."
            mc "No, I meant like, what do I fill in?"
            s "Oh. There should be files in the department's archive room. It should have the proper information, and you can just write whatever it says onto the form."
            s "Each paper should have an ID number on it, and that matches with a specific file. Can I see one of the forms?"
            mc "(Sigma finally looks up from her papers, but at that moment I realized I hadn't brought any of the forms with me. Regret fills my mind as I quickly look away from Sigma.)"
            mc "I, uh. I didn't bring them with me."
            mc "(She looks surprised. She begins to frown, but quickly stops and returns to a neutral expression.)"
            s "No, it's fine. You're new here. And everyone makes mistakes sometimes."
            mc "(Her voice is covered in mild annoyance. I start to feel bad about myself, and it seems that it showed on my face.)"
            s "Don't worry about it. There are other ways you can help, like..."
            mc "(She begins shuffling around her papers to try to find something I can do.)"
            mc "No, it's fine, I can just-"
            mc "(Sigma cuts me off with a few sheets that had been paper-clipped together.)"
            s "Here, you can do these. They're the company tax forms. And these..."
            mc "(She places a folder and a ballpoint pen on top of the stack.)"
            s "...are the records. Just look through the file for the appropriate paper, and put the information in the form."
            mc "(I grab the stack of papers from her and sit down at the small desk facing opposite the main one.)"
            mc "(Before I even open the files I hear Sigma laugh quietly behind me.)"
            mc "(I turn around inconspicuously to see if she was laughing at me, but she was already back to work.)"
            mc "(Before I sit back down and pretend as if nothing happened, Sigma turns around slightly to look at me. We make eye contact.)"
            mc "(She laughs. This time I'm sure it's at me.)"
            mc "What?"
            mc "(Sigma averts her eyes and turns back to her work.)"
            mc "(I stand in silence, confused by her actions. The silence remains for a few more seconds before she speaks.)"
            s "Sorry about that. That desk is usually reserved for the CEO, on the rare occasion that he shows up."
            mc "Oh."
            mc "(I back away from the desk and look around for another surface to work on.)"
            s "No, it's fine. I doubt the CEO would care much if someone sat at his special desk. Especially if that someone was doing his tax work for him."
            mc "(I don't feel very reassured about this, but I trust Sigma. She doesn't have a reason to lie to me, right?)"
            mc "(I sit back in the seat and get to work.)"
            with fade
            mc "(It's not a lot of work, these tax reports. It's less than a fourth of the stack in my cubicle. I wonder if Sigma gave me less work cause she didn't think I could handle anything else. It hurts that I'm not seen as terribly competent, but it is a proper assessment of my skill level.)"
            mc "(Every once in a while, I come across something that I don't understand. Sigma is always ready to help, but the sarcastic way she explains it makes me feel uncomfortable whenever I need to ask her something often.)"
            mc "(I can tell that she means no harm when she acts like that, but it still makes me nervous about taking too much.)"
            with fade
            mc "(I finally finish the papers. The massive floor-to-ceiling windows of the main lobby shine a golden-red light onto the ground, forming a carpet-like shape onto the floor of the lobby. The hues make me feel nostalgic for a memory I don't have, but it's a good indicator of when my shift ends.)"
            mc "(I get up from my chair with a yawn to hand the papers to Sigma.)"
            mc "I finished the tax papers, Sigma."
            mc "(I stack the papers on top of the file folder and place the pen on top of the stack.)"
            s "Thanks."
            mc "(She gives me a thumbs-up with her free hand before going back to work.)"
            s "You can leave now if you want. You don't get paid for any work after 5 pm."
            mc "(I leave the desk area and walk to the main lobby, ready to go home.)"
            mc "(Sigma's still working, though. I wonder if secretaries get paid differently.)"
            mc "Are you gonna stay?"
            s "Yeah. I need to finish up all of this."
            mc "(She motions at the various stacks of paper covering her desk. It seems like a lot of work. It'd probably take me a week to do even half of it.)"
            mc "Good luck, I guess."
            s "Thanks."
            mc "(I wave her goodbye and head out the door. The sky is slowly but surely beginning to darken. I need to hurry home to escape the night.)"
    with fade
    mc "(I'm back at the apartment building. The stairs feel taller than they did this morning because of how tired I am. It's not a good feeling, but it is nice to be able to say that I did work today.)"
    mc "(I walk over to apartment 308 and unlock the door.)"
    "door sound"
    mc "(I'm home again. It certainly feels different coming back here then coming back to my hospital room. I feel like I own something now. Plus, it just feels better that I'm not bleeding money into the healthcare system.)"
    mc "(Do I need to wash these clothes? I'm pretty sure Sigma said that technically I didn't need to wear business formal every day.)"
    mc "(I'll just wash these and wear my casual clothes tomorrow.)"
    mc "(I change back into my normal clothing and throw the formal clothes into the washer.)"
    mc "(Do I have anything else to eat in the house? Hopefully that cool guy snuck into my house and made me dinner, or something. Actually, I hope that didn't happen.)"
    mc "(I look through the fridge for something to eat, and luckily I find something. It's... macaroni and cheese.)"
    mc "(I pull the bowl of it out from the fridge and put it in the microwave. After it's fully heated up, I bring it to the armchair and turn on the TV.)"
    mc "(Nothing beats eating dinner while watching TV. It's not like doing either of those things is bad on their own. Combining them is better than both, though.)"
    with fade
    mc "(After I finish my food, there's not much to do. Most of the TV channels are boring, and the few shows it has aren't to my tastes.)"
    mc "(I surf through the channels a couple more times before finally deciding to go to sleep. I should get a hobby or something.)"
    mc "(I change into my pajamas and get into bed.)"
    mc "(Quite a bit happened today, didn't it? Is the rest of my life going to be like this? Every day, I wake up, eat, go to work, return, eat, and sleep. I don't want that. That sounds like an awfully plain way of living out the rest of my life.)"
    mc "(I turn onto my side and go to sleep.)"
    with fade
    mc "(The next day, a problem came up.)"
    mc "(I didn't have anything to eat. The fridge was empty and there was no magical plate of eggs that appeared on my counter. I suppose that's a good thing, though. It means that no one sneaked into my apartment while I was asleep.)"
    mc "(I changed into my casual clothes and set out for work immediately. It was early in the morning, so I wasn't feeling the pain of hunger yet.)"
    with fade
    mc "(I arrived earlier than I had yesterday. The sun was a mellow tone, gently lighting up the earth without too much heat.)"
    mc "(I entered the office, and Sigma is lying down on the desk. It seems that she was sleeping until I opened the door.)"
    mc "Good morning."
    mc "(She rubs her eyes and yawns before she sits up. She looks pretty different without her glasses. I can't tell what's different, but she doesn't look the same.)"
    s "Good morning."
    mc "(She sounds really tired. She almost definitely stayed here overnight. The amount of papers on her desk has dramatically decreased though. I guess her all-nighter paid off.)"
    mc "(She rubs her eyes again before putting on her glasses. After a brief pause she gets back to work.)"
    mc "(I leave Sigma to do her work and walk through the main department of the office to the Disease Management department.)"
    mc "(Now comes the task of filling out the records. I'm pretty sure I know what I'm doing.)"
    mc "(I write down the ID numbers, grab the correct files, and all I need to do is fill out the forms.)"
    with fade
    mc "(I've been doing this for hours now. I'm pretty sure it's time for lunch now.)"
    mc "(I guess I'll go with Joe Joe. I bet he knows where the good restaurants are.)"
    mc "(I stand up to get his attention, but he's not at the cubicle he was in yesterday. I guess that wasn't his cubicle or something.)"
    mc "(If he's not here, then he should probably be at the water cooler. That guy likes his water.)"
    mc "(I head towards the corner of the department, into the break corner. And sure enough, I spot an aggressively average man drinking coffee instead of water. He spots me too, and waves at me.)"
    j "Hey, [name]. What's up?"
    mc "Wanna go get lunch together?"
    j "Oh, is it lunchtime already?"
    mc "(He glances at his watch. After confirming the time, he quickly drinks the rest of his coffee and wipes his mouth.)"
    j "Alright, let's go."
    mc "(We begin walking towards the entrance together.)"
    j "You're new, right? I'll show you all the good places to eat around here. What do you want to eat today?"
    mc "I don't know. We can just go wherever you want."
    j "Okay. Prepare for the greatest eating experience you've ever had!"
    mc "(After a few more bits of small talk, we reach the main lobby. Sigma is still working, even though it's lunch break.)"
    mc "(Joe Joe seems to notice her. A slight smile appears on his face.)"
    j "Sigma!"
    mc "(His sudden shout makes Sigma twitch. She stops her typing for a moment.)"
    s "What do you want, Joe Joe?"
    j "I saw that you were still working, even though it's lunch break. Wanna come have lunch with us?"
    mc "(Sigma looks up from her computer to look at us. She stares at me for a second before she sighs.)"
    s "I don't need to eat, Joe Joe. I can absorb energy from the sun."
    mc "(She powers down her computer and adjusts her glasses.)"
    s "But... I do enjoy food every once in a while."
    mc "(She walks around the front desk and joins us.)"
    s "Where are we going?"
    mc "(Joe Joe smiles and we start walking out the door.)"
    j "Since [name] is new here, and they haven't had lunch yet, I was thinking that we show them the best place to eat right off the bat."
    s "Right. And that place is?"
    j "The pizzeria, of course!"
    mc "(Sigma doesn't look terribly happy about that. The two are like day and night.)"
    s "You'd want to leave a good impression on our new-hire here, right? Why not go to an actual good restaurant?"
    mc "(Sigma points at a burger joint at the corner of the street.)"
    s "I'm sure we'd all enjoy this lunch break better if we went to a burger place."
    mc "(Now it's Joe Joe's turn to look dissatisfied. It seems like these two have very strong opinions about their lunch spots.)"
    j "I certainly would not enjoy that. That place is so expensive, and the food isn't even that great. The oil gets all over my hands."
    s "That's cause you don't wrap the burger in napkins. If you don't want oily hands, then take the step to protect yourself. That's not a valid point. Besides, isn't pizza oily as well? Considerably more oily than burgers?"
    j "Only if you order an oily pizza. They're not all like that. Even if they were..."
    mc "(The two continue to argue for a while until they finally decide to drag me into their debate.)"
    j "Okay, [name]. You can decide which one is better. Prove to Sigma that she's wrong."
    s "Mine's the correct answer. Make the right choice, [name]."
    menu:
        "Sigma's right.":
            mc "Sigma's right. Let's go to the burger place."
            s "See? I told you so."
            mc "(Sigma's voice is coated in smugness. I can almost imagine her pulling her eyelid down and sticking her tongue out with how cocky her voice is.)"
            j "Fine."
            mc "(Joe Joe, on the other hand, isn't doing very well. He admitted defeat, but he still seems annoyed at Sigma's smug attitude. I feel bad for him since I kinda betrayed him with that decision. He probably really wanted to eat pizza today.)"
            mc "(Sigma starts walking towards the burger joint at a brisk pace, forcing us to follow behind her.)"
            mc "(Her antennae are moving around swiftly and have turned a bright green color. I assume that means she's happy. It's pretty cute.)"
            mc "(We enter the burger joint. It doesn't seem like Joe Joe has ever been here, but Sigma certainly looks like she has. She immediately heads for the back of the line. She probably already knows what she wants.)"
            mc "(It doesn't matter though. There are only a few people in the store, giving us enough time to think about our order without forcing us to wait too long.)"
            mc "(That reminds me. I'll need to ask for money to pay for my food. I'll just get the cheapest options here.)"
            mc "(I get into line behind Sigma and tap on her shoulder to ask for money.)"
            mc "Sigma, can I borrow some money?"
            s "Hm? Sure, how much?"
            mc "Just enough to cover my meal. It's a long story, but I don't have money right now."
            mc "(She looks like she's about to question me, but decides against it. She nods and gives me a thumbs-up.)"
            mc "Thanks. I promise I'll pay it back."
            mc "(Joe Joe hasn't gotten in line yet. He's still thinking about his order. He should probably get in line since a bunch of people just entered the store. They're probably on their lunch break too.)"
            mc "Joe Joe."
            mc "(He doesn't notice.)"
            mc "Joe Joe!"
            mc "(When he finally looks over at me, the other group of people have already reached the back of the line. He frantically walks over to the line, but it's too late. They're not letting him cut.)"
            s "Hey."
            mc "(While I'm distracted by Joe Joe, Sigma has already ordered our food. She's tapping on my shoulder to get my attention.)"
            s "I already got your food, by the way."
            mc "(She walks over to an empty table and sets our food down. Joe Joe will be stuck in burger purgatory for now, it seems. I'm sure he'll be fine.)"
            s "You didn't tell me what you wanted, so I got you the same thing I have."
            mc "That's fine, I don't mind. How much was it?"
            s "Like, $10 or something. It doesn't matter."
            mc "I was gonna ask you to get me something cheap, cause I don't want to spend too much of your money."
            s "No, it's fine. I have enough money to spare, and it feels good that I could help one of my coworkers."
            mc "(I grab one of the burgers off the tray. Sigma does the same. Since we have the same meal, it doesn't matter which one I pick.)"
            mc "(I take a bite out of it. It's pretty good. I don't know if it's worth ten dollars of Sigma's paycheck, but it's decent.)"
            mc "(The entire meal can be described as \"decent\". The fries taste about as good as fries can, and the soft drink feels watered down from all the ice. But overall, it's not that bad, at least in my opinion.)"
            mc "(Sigma seems to be enjoying it more than I am. She seems more energetic than usual, and her antennae are lightly swaying to match her mood.)"
            mc "(She looks very pretty whenever she smiles. Not that she doesn't look good all the time, but she especially looks nice like this. Plus, it makes me feel better that I sort of helped her feel happy. Her face is quite beautiful, though. Her elegance puts Aphrodite to shame. I would eat burgers every day if I get to see Sigma like this. That's not particularly healthy for my body though, so it's more of a dream scenario.)"
            mc "(Her happiness has spread to me. I hope I'm not smiling like a maniac, but I can't help it when I see something so amazing.)"
            j "Hey guys, I finally got my food!"
            mc "(Joe Joe comes barging in, interrupting my Sigma watching. I quickly look away, hoping that he didn't see me staring at her.)"
            mc "Nice. What'd you get?"
            j "Just a random burger. It wasn't that expensive, so it probably doesn't taste that good. But hey, you never know until you try, right?"
            mc "(Sigma, still eating her burger, gives Joe Joe a thumbs-up. She doesn't even bother talking to him.)"
            j "I hope this is good. Surely it can't be that bad, right? Probably not better than pizza, but it's still fast food."
            mc "(He takes a small bite from the burger. His expression barely changes, so I can't tell what he thinks of it yet.)"
            mc "(Finally, he swallows the bite.)"
            j "Not bad."
            mc "(We finish our food and head back to the office to work again.)"
            with fade
            mc "(Time to get back to work. It's more paperwork. Lucky me…)"
            mc "(At least I know how to properly fill it out. Can't say the same for me of yesterday.)"
            mc "(Lunch is pretty fun, though. It's nice being able to eat with friends. I'll be hanging out with Joe Joe and Sigma every day from now on, I guess.)"
            with fade
            mc "(Is it sunset already? Time goes faster if I'm doing paperwork, it seems. That or I just fell asleep.)"
            mc "(I should probably go buy some food for tomorrow. I can probably get my paycheck earlier, right? It's not like I'd be taking more money. I'll ask Sigma about it.)"
            mc "(I head to the front desk, this time going in front of it.)"
            mc "(Just like yesterday, Sigma's still working on something. At least the stacks of paper on her desk seem to have lessened in number.)"
            mc "Hey, Sigma."
            s "Yeah."
            mc "Can I get money right now?"
            s "Huh? No…?"
            mc "Sorry, I meant, like. Can I get my paycheck right now? I need money to buy groceries."
            s "I don't think you can? The CEO signs all the checks at once, so I'll need to ask him. I'm not sure."
            s "I can give you my money if you want. Just pay it back when you get paid."
            mc "Thank you so much, Sigma."
            s "This should be enough to cover a week's groceries, right?"
            mc "(She hands me a $50 bill, neatly folded directly in half.)"
            mc "Thank you."
            mc "(I take the bill and head out the door.)"
            mc "(Just like yesterday, the sun is already setting when my shift ends. Since I'll be home after dark no matter what, I don't bother to rush.)"
            mc "(There's a small corner store on the way back. I'll check it out.)"
            mc "(It's only a few streets away from the office, so I could also go there for lunch. I'd probably be more lonely than if I went to an actual restaurant, but at least it's an option.)"
            mc "(It's not even a 5-minute walk. I should come here more often.)"
            mc "(The automatic doors slide open and a sound plays throughout the store, alerting the cashier of my presence.)"
            "Cashier" "Welcome!"
            mc "(I look around the store. I'd rather not spend too much time here, so I should be quick. The food at the front is all instant ramen and bottled drinks. I'll just take some of them.)"
            mc "(I only need to buy breakfast and dinner, but I should still save money for lunch. I don't want to borrow too much money from Sigma.)"
            mc "(I check out my items and leave the store.)"
        "Joe Joe's right.":
            mc "Joe Joe's right. Let's have some pizza."
            j "Yes! I knew you were on my side."
            mc "(Joe Joe pumps his fist and starts gloating.)"
            j "Take that, Sigma. You should've known that I was right from the beginning."
            mc "(Sigma looks quite sour about my choice. Her antennae turn slightly redder, and she looks at me like I've betrayed her.)"
            s "Ugh, fine. Let's go, I guess."
            mc "(Joe Joe is doing much better. His brightness is kicked to the max and he begins pulling out his wallet to pay for the food.)"
            mc "(The pizzeria is farther than the burger place, but not by much. We have plenty of time, anyways.)"
            with fade
            mc "(Joe Joe's excitement for pizza increases by the second. His child-like joy about pizza makes me happy as well.)"
            j "Do you guys want multiple pizzas or one large pizza?"
            s "Who cares, it's just pizza."
            mc "Is there any difference between them?"
            j "The smaller pizzas are more food per person, but each slice is smaller. Unless you want to consider the entire pizza one slice, I guess. The large pizza would be cheaper and each slice would be larger. They should be around the same price if we're only ordering for 3 people."
            mc "Let's get..."
            menu:
                "The small pizzas":
                    $ smallpizza = True
                "The large pizza":
                    $ smallpizza = False
            j "Sure thing. Let's get in line."
            s "I'll wait for you guys at a table. Just get me whatever."
            mc "(She sits down at a table right next to the window and pulls out her phone.)"
            j "You can sit down too if you want. What do you want?"
            mc "No, I'll wait with you. I'd feel bad if you had to wait here all alone."
            if smallpizza:
                j "Do I look like someone who would order small pizzas all by myself?"
                mc "(To be honest, he looks plainer than cheese pizza, so I can't answer that question.)"
                j "Anyways, I'll just get pepperoni on the pizzas. You're okay with that, right?"
            if not smallpizza:
                j "Do I look like someone who would order a large pizza all by myself?"
                mc "(To be honest, he looks plainer than cheese pizza, so I can't answer that question.)"
                j "Anyways, I'll just get pepperoni on the pizzas. You're okay with that, right?"
            mc "Yeah, that should be fine."
            j "Perfect."
            mc "(It takes some time, but we place the order and get our food.)"
            mc "(We sit down at the table and begin to eat.)"
            mc "(The pizza tastes pretty good. It's quite hot since it just got out of the oven, but it's fine if I just blow on it.)"
            mc "(Sigma doesn't seem to care about the temperature. She's still on her phone, only grabbing the pizza with her left hand so she doesn't get oil on the screen.)"
            mc "(Joe Joe seems the same way, though I think it's more of him loving pizza rather than not caring about the heat. The way he eats could make any food look delicious. He reminds me of a young child, excited by things as simple as pizza for lunch.)"
            mc "(His expression is that of bliss, like a buddhist who has achieved nirvana. I really wanna ruffle his hair, but I think he'll find it weird.)"
            mc "(He's already finished his slices, sadly. I wish I had more time to watch him. What a quick eater.)"
            mc "(His satisfied look is enough for me though. His cheeks are a rosy pink color, and he smiles contently as he drinks a glass of water.)"
            mc "(He wipes his mouth with a paper napkin and yawns. I continue staring at him until he finally looks up at Sigma and I to see if we're done eating.)"
            mc "(He looks at me blankly. I can't tell if he saw me staring at him, but then he looks at Sigma. A slight smile appears on his face.)"
            j "I thought you could get energy from the sun. Why are you still eating pizza if it's so bad?"
            mc "(Sigma finally looks up from her phone, scowling at Joe Joe.)"
            s "That was a joke. And besides, I don't like pizza, but it's not like it's bad. I'm fine with eating it, I just like other foods more."
            mc "(She wrapped the pizza in multiple layers of napkins, but even so there's still some oil on her fingers. She has to wipe it off on yet another napkin before touching anything.)"
            mc "(Once we finish our food, it's time to head back to work. On the way back, Joe Joe still is excited, but as the office building comes into sight his enthusiasm begins to die down.)"
            mc "(Everyone returns to their work mindset. Sigma returns to the front desk and Joe Joe heads off to who-knows-where to do some sort of work.)"
            mc "(I sit back down at my cubicle and begin filling out the records again.)"
            mc "(Now that I think about it, I should've asked Sigma or Joe Joe for money. I won't be having breakfast or dinner until I get paid. I don't want to act like a leech, but I kinda need food to survive.)"
            mc "(Sigma's at the front desk, but I don't want to ask her. I probably annoyed her since we didn't get burgers today. That leaves Joe Joe. He's probably at the water cooler, now that I think about it. He hasn't consistently appeared anywhere else.)"
            mc "(I head over to the water cooler for the second time today. Strangely, Joe Joe is nowhere to be found. This scene feels off without Joe Joe. I can't tell what's wrong, but it just seems weird without Joe Joe at the cooler. I'm sure he's a busy man though, so he probably went elsewhere for now.)"
            mc "(Throughout the remainder of the day, I keep looking over at the break corner to try to find Joe Joe. I know he's probably fine, but I can't help but feel anxious about his disappearance.)"
            mc "(It's now the end of my shift and I still haven't seen Joe Joe again. I'll just ask him tomorrow.)"
            mc "(Just like yesterday I leave the building, waving Sigma goodbye. I start to think about where I could go shopping once I ask Joe Joe tomorrow. I know there's a small convenience store on the way home from here, and there's also a grocery store close to the apartment building. I'm sure there are other places as well.)"
            mc "(Right before I head home, I spot something in the bushes outside the building. It's…)"
            mc "(A folded $50 bill, caught on the leaves.)"
            mc "(It looks like it's my lucky day and someone else's unlucky day. I wonder who could've lost this?)"
            mc "(I look around, trying to spot anyone who could be the owner of this bill. No one's around. The closest person is all the way across the street and they're closer to the bush.)"
            mc "(It's in such an odd position too. I doubt anyone could unintentionally leave a $50 bill on the bushes unless they got tackled into them. Yeah, someone probably felt generous today and left some money for a stranger. My heart goes out to the kind individual who did such a selfless act.)"
            mc "(I snatch the bill away from the branches and put it into my pocket. I should be able to buy food now.)"
            mc "(The sky is darkening quickly, so I have to hurry. The closest store should be… that way.)"
            with fade
            mc "(The automatic doors slide open gently, ringing an electronic doorbell throughout the store. The young cashier welcomes me without a hint of life in his voice. I feel bad for him, but he probably only does this part-time.)"
            mc "(There isn't much in the store that I would want to eat. It's mostly frozen food, but there are some instant ramen cups. Most of the frozen food looks average at best, but there are some seemingly good meals among them.)"
            mc "(I grab a couple of ramen cups and some frozen pizza. It should be enough to last me this week. I'll get some candy as well.)"
            mc "(In total, it uses up around half of my money. I'll save the rest for lunch and other expenses.)"
            mc "(After that mini-shopping spree, it's finally time to head back home. The doors slide open and I step outside.)"





 

