label day1work:
    mc "(The building is in sight now. That only took around 20 minutes, I think.)"
    "The MC is outside of the DEEZ Corp building."
    mc "(What a tall building. It's the tallest one on the block.)"
    mc "(No one's walking into the building. I'm getting a bit nervous.)"
    mc "(Am I in the right place? I check the map again, certain that I read it wrong, yet every street marker and building tells me that I'm at the correct location.)"
    mc "(I should be more confident. No one would walk into an office building if they don't work there, right? I'm one of the few people who has the right to go in.)"
    mc "(I adjust my already correctly adjusted tie and step through the automatic doors.)"
    mc "(My face is hit by a light sweep of air conditioning. It's a comfortable feeling for an office building, but it's already cold outside.)"
    mc "(Right in front of the entrance is a medium-sized desk. There's a woman sitting at the desk, typing on her computer.)"
    mc "(Even though she's looking down, I can tell that she's beautiful. Both her clothes and her hair are very finely kept.)"
    mc "(I adjust my tie again and walk up to the front desk.)"
    mc "H-Hello."
    "The woman at the desk" "..."
    mc "(Did she hear me?)"
    mc "(I sit in silence while the woman types on her computer for a few more seconds.)"
    mc "(She finally looks up at me, but she looks back to her screen.)"
    mc "(Wow, she's even prettier close up. Her eyes are nice. At least a 10, maybe even an 11.)"
    mc "(After a few more seconds, she stops typing and leans back to look at me.)"
    "Woman" "How may I help you?"
    mc "I recently got hired to work here. "
    "Woman" "Mhm."
    mc "(She carefully studies my clothes, as if she's scanning for every single imperfection in my outfit.)"
    mc "(I think I see the slightest bit of a frown appear on her face, but it's so slight that I can't tell if I was just seeing things.)"
    mc "(Her antennae twitch before she finally breaks the silence.)"
    "Woman" "Welcome to the company. I'm Sigma."
    s "I'll give you a tour."
    mc "(She gets up from her chair and walks around the desk area.)"
    s "Follow me."
    mc "(She turns around on her heels and walks away at a rapid pace.)"
    mc "(I have to run to catch up with her.)"
    s "If you're the same [name] as the files tell me, you're working as a Charitable Urgency Manager. If there's a disease that someone needs handling, it's your job to suit their needs and help them. Work starts at 9 am sharp every weekday, but sometimes you might get called in on the weekends."
    s "You don't need to follow the dress code every day, by the way. I would like it if you wore a suit every day, but the quality managers only check once a month."
    mc "(Finally, Sigma pauses in front of a department layered with cubicles.)"
    s "Charitable Urgency Managers are grouped in with the Disease Management section. Most of these guys deal with the paperwork though. You should probably make as many friends with them as possible."
    mc "(She walks around the lines of cubicles until she finds one without a name labeled on the chair.)"
    s "This one will be yours. You can put your personal belongings underneath your desk, but be careful not to let them move outside of your designated area."
    mc "(Sigma starts to walk away before she suddenly stops.)"
    s "Oh, I forgot to mention. You'll get an hour break at 12 for lunch and other stuff, but you can also take a 5-minute break whenever you want. You only get two per workday, though. Don't waste them."
    mc "(Sigma gestures for me to follow her before she walks toward the back of the department.)"
    s "Here is the broken corner."
    mc "(There's a small coffee machine on the desk and a water cooler right next to it.)"
    mc "(I reach for a paper cup, but I suddenly bump into another person doing the same thing.)"
    mc "Oh, sorry."
    "Other guy" "Sorry."
    mc "(I let him take the cup first since he was there first.)"
    mc "(But he does the same thing, for some reason. I'll accept his act of kindness.)"
    mc "(I reach for the cup again, but he does the same. Our hands bump into each other.)"
    mc "(I look up at this strange man who mirrors my every action.)"
    show joejoe
    mc "(Have I seen this guy before?)"
    mc "(Wasn't he one of the people I passed on the way here? Or was he the guy back at the cubicle?)"
    "Incredibly average man" "I'll go ahead."
    mc "(He grabs a paper cup while I'm trying to remember who he is, and fills it up silently.)"
    s "That's Joe Joe, one of your co-workers. I honestly can't remember when he got here, or what he does, but he frequents the water cooler every break."
    mc "(Joe Joe downs his water cup in a single gulp. He looks satisfied with his amount of water, even though I could probably hold more in my bare hands.)"
    j "Nice to meet you."
    j "Sorry about those water cooler shenanigans. I'm not the best at interacting with other people."
    mc "(Sigma walks away without a sound, leaving me to deal with someone I've just met.)"
    mc "(He sips the cup again, only taking in the few remaining droplets.)"
    j "I see you've already met Sigma. She's a hard worker, that woman."
    mc "(He laughs quietly before filling up his cup again.)"
    j "I assume you're new to this place. What's your name?"
    mc "I'm [name]. Nice to meet you."
    j "Nice to meet you too. If you're confused about something, you can just ask me about it."
    menu: 
        "What do you do here?":
            mc "(His face shows a hint of surprise before he smiles again.)"
            j "Oh, this will sound kinda bad, but..."
            j "I'm not sure."
            mc "Huh?"
            j "No, I mean, like, I come here every day, right?"
            j "And every day Sigma allows me in without a hitch."
            j "But I don’t do anything for the company. I just wander around for the entire day. Sometimes I help someone with paperwork or run errands for them, but I’m not paid to do that."
            j "I work for the company, but I don't {i}work{/i} for the company. Y'know what I'm saying?"
            j "Oh, I do go get lunch with the crew every once in a while."
            mc "...I see."
            mc "(Why is he even getting paid?"
        "What do I do here?":
            j "I don't know. Did Sigma tell you your position or anything?"
            mc "Yeah, she said I was a Cherishable Undergraduate Major or something like that."
            mc "(His face lights up like a candle once I say that.)"
            j "Ah, yes, the Charitable Urgency Managers. I always loved that title."
            j "I believe you're the ones who handle the diseases. Like, fighting them and whatnot."
            j "But that doesn't happen that often, so I think you just spend most of your time doing paperwork."
            mc "That sounds like a pain."
            j "Yeah, it does."
        "I'm good.":
            j "Glad I could... help?"
            mc "(He looks a bit crestfallen that I didn't ask anything. I feel bad for him now."
    j "Anyways, welcome to the company. I look forward to working with you. I’ll be your water cooler buddy too, I guess."
    menu:
        "Sure."
            mc "(He nods and waves at me as he walks away.)"
        "No thanks."
            mc "(He gives me a thumbs up and walks away.)"
    mc "(He gives me a thumbs-up and walks away.)"
    mc "(Now I'm alone at the water cooler.)"
    mc "(I should probably do work now.)"
    with fade 
    mc "(I depart from the break corner and head towards the cubicle that Sigma assigned to me.)"
    mc "(Everybody in this cubicle group is working on something. I sit down as quietly as I can to not bother them.)"
    mc "(No one's around this area except for a single man in the cubicle in front of mine. I guess the other Charitable Urgency Managers are on break or something.)"
    mc "(There's a stack of papers on my desk. It's quite a bit of paper, but it doesn't seem like it would be that difficult.)"
    mc "(I look through the papers to see what I have to do, but they're all completely blank.)"
    mc "(Name, Date of Birth, Disease. They're all important information, but I don't have any information to put in the form.)"
    mc "(I shift around the papers to try to find anything that can help me, but they're forms.)"
    mc "(I keep looking around the papers to see if I had just missed one. Nothing. I check underneath my desk to see if I dropped one. Nothing.)"
    mc "(What do I do...)"
    menu:
        "Ask a coworker":
            mc "(I stand up from my chair so I can see the cubicle in front of me.)"
            mc "(He looks like he's hard at work. Maybe I shouldn't bother him…)"
            mc "(But I have no choice. I don't want to sit here for another 3 hours without anything to do.)"
            mc "Hey."
            mc "(I don't think he heard me.)"
            mc "Hey, you."
            mc "(He looks up from his papers.)"
            mc "(His face reminds me of Joe Joe.)"
            mc "(He has the same brown hair and light blue shirt. The same dark blue pants. He even has a cup of water next to him.)"
            mc "(Wait…)"
            j "Oh, hey [name]! What's up?"
            mc "Oh, it's you."
            mc "Uh, I was wondering, what am I supposed to do for this?"
            mc "(I show him a paper from my stack. He glances over it, then turns it around.)"
            j "Oh for these, you need to get files from the archive. Do you see how each sheet has an ID on it? That corresponds with their file number."
            mc "Thanks."
            j "No problem. The file archive should be right outside the department. You should be able to see the files through the windows."
            mc "(I try to scoop up the stack of papers before realizing I can just write down the ID numbers.)"
            mc "(After that, I head towards the archive room to grab some files.)"
            mc "(All of the people I need to document have ID numbers in the 10000s. I don't think I'll get through all of them though, so I only take the first 10 I need.)"
            mc "(I head back to my cubicle and begin filling out the forms for each and every person.)"
            with fade
            mc "(It takes a lot longer than I expected. I didn't know just how much information we had to record on these people.)"
            mc "(And to think that there are at least 10,000 different files…)"
            mc "(By the time I finish the 9th file, it's already dark outside, and my shift is over.)"
            mc "(I yawn as I get up from my desk. This job isn't difficult, but it sure is a lot of work.)"
            mc "(I need to return these files to the archive room, and then I can leave.)"
            mc "(After I do that, I head for the main lobby.)"
            mc "(When I pass the front desk, I can see that Sigma is still working hard. I guess she ends her shift later, or maybe she just likes working.)"
            s "{size=-10}Fuck this shit. This fucking sucks so bad.{/size}"
            mc "(Yeah, her shift probably ends later.)"
            mc "(I'd rather not bother her while she's working.)"
            mc "(I leave the building and head home.)"
 

