label day1work:
    mc "(The building is in sight now. That only took around 20 minutes, I think.)"
    "The MC is outside of the DEEZ Corp building"
    mc "(What a tall building. It's the tallest one on the block.)"
    mc "(No one's walking into the building. I'm getting a bit nervous.)"
    mc "(Am I in the right place? I check the map again, certain that I read it wrong, yet every street marker and building tells me that I'm at the correct location.)"
    mc "(I should be more confident. No one would walk into an office building if they don't work there, right? I'm one of the few people who has the right to go in.)"
    mc "(I adjust my already correctly adjusted tie and step through the automatic doors.)"
    mc "(My face is hit by a light sweep of air conditioning. It's a comfortable feeling for an office building, but it's already cold outside.)"
    mc "(Right in front of the entrance is a medium-sized desk. There's a woman sitting at the desk, typing on her computer.)"
    mc "(Even though she's looking down, I can tell that she's beautiful. Both her clothes and her hair are very finely kept.)"
    mc "(I adjust my tie again and walk up to the front desk.)"
    mc "H-Hello."
    "The woman at the desk" "..."
    mc "(Did she hear me?)"
    mc "(I sit in silence while the woman types on her computer for a few more seconds.)"
    mc "(She finally looks up at me, but she looks back to her screen.)"
    mc "(Wow, she's even prettier close up. Her eyes are nice. At least a 10, maybe even an 11.)"
    mc "(After a few more seconds, she stops typing and leans back to look at me.)"
    "Woman" "How may I help you?"
    mc "I recently got hired to work here. "
    "Woman" "Mhm."
    mc "(She carefully studies my clothes, as if she's scanning for every single imperfection in my outfit.)"
    mc "(I think I see the slightest bit of a frown appear on her face, but it's so slight that I can't tell if I was just seeing things.)"
    mc "(Her antennae twitch before she finally breaks the silence.)"
    "Woman" "Welcome to the company. I'm Sigma."
    s "I'll give you a tour."
    mc "(She gets up from her chair and walks around the desk area.)"
    s "Follow me."
    mc "(She turns around on her heels and walks away at a rapid pace.)"
    mc "(I have to run to catch up with her.)"
    s "If you're the same [name] as the files tell me, you're working as a Charitable Urgency Manager. If there's a disease that someone needs handling, it's your job to suit their needs and help them. Work starts at 9 am sharp every weekday, but sometimes you might get called in on the weekends."
    s "You don't need to follow the dress code every day, by the way. I would like it if you wore a suit every day, but the quality managers only check once a month."
    mc "(Finally, Sigma pauses in front of a department layered with cubicles.)"
    s "Charitable Urgency Managers are grouped in with the Disease Management section. Most of these guys deal with the paperwork though. You should probably make as many friends with them as possible."
    mc "(She walks around the lines of cubicles until she finds one without a name labeled on the chair.)"
    s "This one will be yours. You can put your personal belongings underneath your desk, but be careful not to let them move outside of your designated area."
    mc "(Sigma starts to walk away before she suddenly stops.)"
    s "Oh, I forgot to mention. You'll get an hour break at 12 for lunch and other stuff, but you can also take a 5-minute break whenever you want. You only get two per workday, though. Don't waste them."
    mc "(Sigma gestures for me to follow her before she walks toward the back of the department.)"
    s "Here is the broken corner."
    mc "(There's a small coffee machine on the desk and a water cooler right next to it.)"
    mc "(I reach for a paper cup, but I suddenly bump into another person doing the same thing.)"
    mc "Oh, sorry."
    "Other guy" "Sorry."
    mc "(I let him take the cup first since he was there first.)"
    mc "(But he does the same thing, for some reason. I'll accept his act of kindness.)"
    mc "(I reach for the cup again, but he does the same. Our hands bump into each other.)"
    mc "(I look up at this strange man who mirrors my every action.)"
    show joejoe
    mc "(Have I seen this guy before?)"
    mc "(Wasn't he one of the people I passed on the way here? Or was he the guy back at the cubicle?)"
    "Incredibly average man" "I'll go ahead."
    mc "(He grabs a paper cup while I'm trying to remember who he is, and fills it up silently.)"
    s "That's Joe Joe, one of your co-workers. I honestly can't remember when he got here, or what he does, but he frequents the water cooler every break."
    mc "(Joe Joe downs his water cup in a single gulp. He looks satisfied with his amount of water, even though I could probably hold more in my bare hands.)"
    j "Nice to meet you."
    j "Sorry about those water cooler shenanigans. I'm not the best at interacting with other people."
    mc "(Sigma walks away without a sound, leaving me to deal with someone I've just met.)"
    mc "(He sips the cup again, only taking in the few remaining droplets.)"
    j "I see you've already met Sigma. She's a hard worker, that woman."
    mc "(He laughs quietly before filling up his cup again.)"
    j "I assume you're new to this place. What's your name?"
    mc "I'm [name]. Nice to meet you."
    j "Nice to meet you too. If you're confused about something, you can just ask me about it."
