label day2:
    with fade
    mc "(I'm back at the apartment building. The stairs feel taller than they did this morning because of how tired I am. It's not a good feeling, but it is nice to be able to say that I did work today.)"
    mc "(I walk over to apartment 308 and unlock the door.)"
    "door sound"
    mc "(I'm home again. It certainly feels different coming back here then coming back to my hospital room. I feel like I own something now. Plus, it just feels better that I'm not bleeding money into the healthcare system.)"
    mc "(Do I need to wash these clothes? I'm pretty sure Sigma said that technically I didn't need to wear business formal every day.)"
    mc "(I'll just wash these and wear my casual clothes tomorrow.)"
    mc "(I change back into my normal clothing and throw the formal clothes into the washer.)"
    mc "(Do I have anything else to eat in the house? Hopefully that cool guy snuck into my house and made me dinner, or something. Actually, I hope that didn't happen.)"
    mc "(I look through the fridge for something to eat, and luckily I find something. It's... macaroni and cheese.)"
    mc "(I pull the bowl of it out from the fridge and put it in the microwave. After it's fully heated up, I bring it to the armchair and turn on the TV.)"
    mc "(Nothing beats eating dinner while watching TV. It's not like doing either of those things is bad on their own. Combining them is better than both, though.)"
    with fade
    mc "(After I finish my food, there's not much to do. Most of the TV channels are boring, and the few shows it has aren't to my tastes.)"
    mc "(I surf through the channels a couple more times before finally deciding to go to sleep. I should get a hobby or something.)"
    mc "(I change into my pajamas and get into bed.)"
    mc "(Quite a bit happened today, didn't it? Is the rest of my life going to be like this? Every day, I wake up, eat, go to work, return, eat, and sleep. I don't want that. That sounds like an awfully plain way of living out the rest of my life.)"
    mc "(I turn onto my side and go to sleep.)"
    with fade
    mc "(The next day, a problem came up.)"
    mc "(I didn't have anything to eat. The fridge was empty and there was no magical plate of eggs that appeared on my counter. I suppose that's a good thing, though. It means that no one sneaked into my apartment while I was asleep.)"
    mc "(I changed into my casual clothes and set out for work immediately. It was early in the morning, so I wasn't feeling the pain of hunger yet.)"
    with fade
    mc "(I arrived earlier than I had yesterday. The sun was a mellow tone, gently lighting up the earth without too much heat.)"
    mc "(I entered the office, and Sigma is lying down on the desk. It seems that she was sleeping until I opened the door.)"
    mc "Good morning."
    mc "(She rubs her eyes and yawns before she sits up. She looks pretty different without her glasses. I can't tell what's different, but she doesn't look the same.)"
    s "Good morning."
    mc "(She sounds really tired. She almost definitely stayed here overnight. The amount of papers on her desk has dramatically decreased though. I guess her all-nighter paid off.)"
    mc "(She rubs her eyes again before putting on her glasses. After a brief pause she gets back to work.)"
    mc "(I leave Sigma to do her work and walk through the main department of the office to the Disease Management department.)"
    mc "(Now comes the task of filling out the records. I'm pretty sure I know what I'm doing.)"
    mc "(I write down the ID numbers, grab the correct files, and all I need to do is fill out the forms.)"
    with fade
    mc "(I've been doing this for hours now. I'm pretty sure it's time for lunch now.)"
    mc "(I guess I'll go with Joe Joe. I bet he knows where the good restaurants are.)"
    mc "(I stand up to get his attention, but he's not at the cubicle he was in yesterday. I guess that wasn't his cubicle or something.)"
    mc "(If he's not here, then he should probably be at the water cooler. That guy likes his water.)"
    mc "(I head towards the corner of the department, into the break corner. And sure enough, I spot an aggressively average man drinking coffee instead of water. He spots me too, and waves at me.)"
    j "Hey, [name]. What's up?"
    mc "Wanna go get lunch together?"
    j "Oh, is it lunchtime already?"
    mc "(He glances at his watch. After confirming the time, he quickly drinks the rest of his coffee and wipes his mouth.)"
    j "Alright, let's go."
    mc "(We begin walking towards the entrance together.)"
    j "You're new, right? I'll show you all the good places to eat around here. What do you want to eat today?"
    mc "I don't know. We can just go wherever you want."
    j "Okay. Prepare for the greatest eating experience you've ever had!"
    mc "(After a few more bits of small talk, we reach the main lobby. Sigma is still working, even though it's lunch break.)"
    mc "(Joe Joe seems to notice her. A slight smile appears on his face.)"
    j "Sigma!"
    mc "(His sudden shout makes Sigma twitch. She stops her typing for a moment.)"
    s "What do you want, Joe Joe?"
    j "I saw that you were still working, even though it's lunch break. Wanna come have lunch with us?"
    mc "(Sigma looks up from her computer to look at us. She stares at me for a second before she sighs.)"
    s "I don't need to eat, Joe Joe. I can absorb energy from the sun."
    mc "(She powers down her computer and adjusts her glasses.)"
    s "But... I do enjoy food every once in a while."
    mc "(She walks around the front desk and joins us.)"
    s "Where are we going?"
    mc "(Joe Joe smiles and we start walking out the door.)"
    j "Since [name] is new here, and they haven't had lunch yet, I was thinking that we show them the best place to eat right off the bat."
    s "Right. And that place is?"
    j "The pizzeria, of course!"
    mc "(Sigma doesn't look terribly happy about that. The two are like day and night.)"
    s "You'd want to leave a good impression on our new-hire here, right? Why not go to an actual good restaurant?"
    mc "(Sigma points at a burger joint at the corner of the street.)"
    s "I'm sure we'd all enjoy this lunch break better if we went to a burger place."
    mc "(Now it's Joe Joe's turn to look dissatisfied. It seems like these two have very strong opinions about their lunch spots.)"
    j "I certainly would not enjoy that. That place is so expensive, and the food isn't even that great. The oil gets all over my hands."
    s "That's cause you don't wrap the burger in napkins. If you don't want oily hands, then take the step to protect yourself. That's not a valid point. Besides, isn't pizza oily as well? Considerably more oily than burgers?"
    j "Only if you order an oily pizza. They're not all like that. Even if they were..."
    mc "(The two continue to argue for a while until they finally decide to drag me into their debate.)"
    j "Okay, [name]. You can decide which one is better. Prove to Sigma that she's wrong."
    s "Mine's the correct answer. Make the right choice, [name]."
    menu:
        "Sigma's right.":
            jump burger
        "Joe Joe's right.":
            jump pizza
label burger:
    mc "Sigma's right. Let's go to the burger place."
    s "See? I told you so."
    mc "(Sigma's voice is coated in smugness. I can almost imagine her pulling her eyelid down and sticking her tongue out with how cocky her voice is.)"
    j "Fine."
    mc "(Joe Joe, on the other hand, isn't doing very well. He admitted defeat, but he still seems annoyed at Sigma's smug attitude. I feel bad for him since I kinda betrayed him with that decision. He probably really wanted to eat pizza today.)"
    mc "(Sigma starts walking towards the burger joint at a brisk pace, forcing us to follow behind her.)"
    mc "(Her antennae are moving around swiftly and have turned a bright green color. I assume that means she's happy. It's pretty cute.)"
    mc "(We enter the burger joint. It doesn't seem like Joe Joe has ever been here, but Sigma certainly looks like she has. She immediately heads for the back of the line. She probably already knows what she wants.)"
    mc "(It doesn't matter though. There are only a few people in the store, giving us enough time to think about our order without forcing us to wait too long.)"
    mc "(That reminds me. I'll need to ask for money to pay for my food. I'll just get the cheapest options here.)"
    mc "(I get into line behind Sigma and tap on her shoulder to ask for money.)"
    mc "Sigma, can I borrow some money?"
    s "Hm? Sure, how much?"
    mc "Just enough to cover my meal. It's a long story, but I don't have money right now."
    mc "(She looks like she's about to question me, but decides against it. She nods and gives me a thumbs-up.)"
    mc "Thanks. I promise I'll pay it back."
    mc "(Joe Joe hasn't gotten in line yet. He's still thinking about his order. He should probably get in line since a bunch of people just entered the store. They're probably on their lunch break too.)"
    mc "Joe Joe."
    mc "(He doesn't notice.)"
    mc "Joe Joe!"
    mc "(When he finally looks over at me, the other group of people have already reached the back of the line. He frantically walks over to the line, but it's too late. They're not letting him cut.)"
    s "Hey."
    mc "(While I'm distracted by Joe Joe, Sigma has already ordered our food. She's tapping on my shoulder to get my attention.)"
    s "I already got your food, by the way."
    mc "(She walks over to an empty table and sets our food down. Joe Joe will be stuck in burger purgatory for now, it seems. I'm sure he'll be fine.)"
    s "You didn't tell me what you wanted, so I got you the same thing I have."
    mc "That's fine, I don't mind. How much was it?"
    s "Like, $10 or something. It doesn't matter."
    mc "I was gonna ask you to get me something cheap, cause I don't want to spend too much of your money."
    s "No, it's fine. I have enough money to spare, and it feels good that I could help one of my coworkers."
    mc "(I grab one of the burgers off the tray. Sigma does the same. Since we have the same meal, it doesn't matter which one I pick.)"
    mc "(I take a bite out of it. It's pretty good. I don't know if it's worth ten dollars of Sigma's paycheck, but it's decent.)"
    mc "(The entire meal can be described as \"decent\". The fries taste about as good as fries can, and the soft drink feels watered down from all the ice. But overall, it's not that bad, at least in my opinion.)"
    mc "(Sigma seems to be enjoying it more than I am. She seems more energetic than usual, and her antennae are lightly swaying to match her mood.)"
    mc "(She looks very pretty whenever she smiles. Not that she doesn't look good all the time, but she especially looks nice like this. Plus, it makes me feel better that I sort of helped her feel happy. Her face is quite beautiful, though. Her elegance puts Aphrodite to shame. I would eat burgers every day if I get to see Sigma like this. That's not particularly healthy for my body though, so it's more of a dream scenario.)"
    mc "(Her happiness has spread to me. I hope I'm not smiling like a maniac, but I can't help it when I see something so amazing.)"
    j "Hey guys, I finally got my food!"
    mc "(Joe Joe comes barging in, interrupting my Sigma watching. I quickly look away, hoping that he didn't see me staring at her.)"
    mc "Nice. What'd you get?"
    j "Just a random burger. It wasn't that expensive, so it probably doesn't taste that good. But hey, you never know until you try, right?"
    mc "(Sigma, still eating her burger, gives Joe Joe a thumbs-up. She doesn't even bother talking to him.)"
    j "I hope this is good. Surely it can't be that bad, right? Probably not better than pizza, but it's still fast food."
    mc "(He takes a small bite from the burger. His expression barely changes, so I can't tell what he thinks of it yet.)"
    mc "(Finally, he swallows the bite.)"
    j "Not bad."
    mc "(We finish our food and head back to the office to work again.)"
    with fade
    mc "(Time to get back to work. It's more paperwork. Lucky me…)"
    mc "(At least I know how to properly fill it out. Can't say the same for me of yesterday.)"
    mc "(Lunch is pretty fun, though. It's nice being able to eat with friends. I'll be hanging out with Joe Joe and Sigma every day from now on, I guess.)"
    with fade
    mc "(Is it sunset already? Time goes faster if I'm doing paperwork, it seems. That or I just fell asleep.)"
    mc "(I should probably go buy some food for tomorrow. I can probably get my paycheck earlier, right? It's not like I'd be taking more money. I'll ask Sigma about it.)"
    mc "(I head to the front desk, this time going in front of it.)"
    mc "(Just like yesterday, Sigma's still working on something. At least the stacks of paper on her desk seem to have lessened in number.)"
    mc "Hey, Sigma."
    s "Yeah."
    mc "Can I get money right now?"
    s "Huh? No…?"
    mc "Sorry, I meant, like. Can I get my paycheck right now? I need money to buy groceries."
    s "I don't think you can? The CEO signs all the checks at once, so I'll need to ask him. I'm not sure."
    s "I can give you my money if you want. Just pay it back when you get paid."
    mc "Thank you so much, Sigma."
    s "This should be enough to cover a week's groceries, right?"
    mc "(She hands me a $50 bill, neatly folded directly in half.)"
    mc "Thank you."
    mc "(I take the bill and head out the door.)"
    mc "(Just like yesterday, the sun is already setting when my shift ends. Since I'll be home after dark no matter what, I don't bother to rush.)"
    mc "(There's a small corner store on the way back. I'll check it out.)"
    mc "(It's only a few streets away from the office, so I could also go there for lunch. I'd probably be more lonely than if I went to an actual restaurant, but at least it's an option.)"
    mc "(It's not even a 5-minute walk. I should come here more often.)"
    mc "(The automatic doors slide open and a sound plays throughout the store, alerting the cashier of my presence.)"
    "Cashier" "Welcome!"
    mc "(I look around the store. I'd rather not spend too much time here, so I should be quick. The food at the front is all instant ramen and bottled drinks. I'll just take some of them.)"
    mc "(I only need to buy breakfast and dinner, but I should still save money for lunch. I don't want to borrow too much money from Sigma.)"
    mc "(I check out my items and leave the store.)"
    jump day3
label pizza:
    mc "Joe Joe's right. Let's have some pizza."
    j "Yes! I knew you were on my side."
    mc "(Joe Joe pumps his fist and starts gloating.)"
    j "Take that, Sigma. You should've known that I was right from the beginning."
    mc "(Sigma looks quite sour about my choice. Her antennae turn slightly redder, and she looks at me like I've betrayed her.)"
    s "Ugh, fine. Let's go, I guess."
    mc "(Joe Joe is doing much better. His brightness is kicked to the max and he begins pulling out his wallet to pay for the food.)"
    mc "(The pizzeria is farther than the burger place, but not by much. We have plenty of time, anyways.)"
    with fade
    mc "(Joe Joe's excitement for pizza increases by the second. His child-like joy about pizza makes me happy as well.)"
    j "Do you guys want multiple pizzas or one large pizza?"
    s "Who cares, it's just pizza."
    mc "Is there any difference between them?"
    j "The smaller pizzas are more food per person, but each slice is smaller. Unless you want to consider the entire pizza one slice, I guess."
    J "The large pizza would be cheaper and each slice would be larger. They should be around the same price if we're only ordering for 3 people."
    menu:
        "Let's get..."
        "The small pizzas":
            $ smallpizza = True
        "The large pizza":
            $ smallpizza = False
    j "Sure thing. Let's get in line."
    s "I'll wait for you guys at a table. Just get me whatever."
    mc "(She sits down at a table right next to the window and pulls out her phone.)"
    j "You can sit down too if you want. What do you want?"
    mc "No, I'll wait with you. I'd feel bad if you had to wait here all alone."
    if smallpizza:
        j "Do I look like someone who would order small pizzas all by myself?"
        mc "(To be honest, he looks plainer than cheese pizza, so I can't answer that question.)"
        j "Anyways, I'll just get pepperoni on the pizzas. You're okay with that, right?"
    if not smallpizza:
        j "Do I look like someone who would order a large pizza all by myself?"
        mc "(To be honest, he looks plainer than cheese pizza, so I can't answer that question.)"
        j "Anyways, I'll just get pepperoni on the pizza. You're okay with that, right?"
    mc "Yeah, that should be fine."
    j "Perfect."
    mc "(It takes some time, but we place the order and get our food.)"
    mc "(We sit down at the table and begin to eat.)"
    mc "(The pizza tastes pretty good. It's quite hot since it just got out of the oven, but it's fine if I just blow on it.)"
    mc "(Sigma doesn't seem to care about the temperature. She's still on her phone, only grabbing the pizza with her left hand so she doesn't get oil on the screen.)"
    mc "(Joe Joe seems the same way, though I think it's more of him loving pizza rather than not caring about the heat. The way he eats could make any food look delicious. He reminds me of a young child, excited by things as simple as pizza for lunch.)"
    mc "(His expression is that of bliss, like a buddhist who has achieved nirvana. I really wanna ruffle his hair, but I think he'll find it weird.)"
    mc "(He's already finished his slices, sadly. I wish I had more time to watch him. What a quick eater.)"
    mc "(His satisfied look is enough for me though. His cheeks are a rosy pink color, and he smiles contently as he drinks a glass of water.)"
    mc "(He wipes his mouth with a paper napkin and yawns. I continue staring at him until he finally looks up at Sigma and I to see if we're done eating.)"
    mc "(He looks at me blankly. I can't tell if he saw me staring at him, but then he looks at Sigma. A slight smile appears on his face.)"
    j "I thought you could get energy from the sun. Why are you still eating pizza if it's so bad?"
    mc "(Sigma finally looks up from her phone, scowling at Joe Joe.)"
    s "That was a joke. And besides, I don't like pizza, but it's not like it's bad. I'm fine with eating it, I just like other foods more."
    mc "(She wrapped the pizza in multiple layers of napkins, but even so there's still some oil on her fingers. She has to wipe it off on yet another napkin before touching anything.)"
    mc "(Once we finish our food, it's time to head back to work. On the way back, Joe Joe still is excited, but as the office building comes into sight his enthusiasm begins to die down.)"
    mc "(Everyone returns to their work mindset. Sigma returns to the front desk and Joe Joe heads off to who-knows-where to do some sort of work.)"
    mc "(I sit back down at my cubicle and begin filling out the records again.)"
    mc "(Now that I think about it, I should've asked Sigma or Joe Joe for money. I won't be having breakfast or dinner until I get paid. I don't want to act like a leech, but I kinda need food to survive.)"
    mc "(Sigma's at the front desk, but I don't want to ask her. I probably annoyed her since we didn't get burgers today. That leaves Joe Joe. He's probably at the water cooler, now that I think about it. He hasn't consistently appeared anywhere else.)"
    mc "(I head over to the water cooler for the second time today. Strangely, Joe Joe is nowhere to be found. This scene feels off without Joe Joe. I can't tell what's wrong, but it just seems weird without Joe Joe at the cooler. I'm sure he's a busy man though, so he probably went elsewhere for now.)"
    mc "(Throughout the remainder of the day, I keep looking over at the break corner to try to find Joe Joe. I know he's probably fine, but I can't help but feel anxious about his disappearance.)"
    mc "(It's now the end of my shift and I still haven't seen Joe Joe again. I'll just ask him tomorrow.)"
    mc "(Just like yesterday I leave the building, waving Sigma goodbye. I start to think about where I could go shopping once I ask Joe Joe tomorrow. I know there's a small convenience store on the way home from here, and there's also a grocery store close to the apartment building. I'm sure there are other places as well.)"
    mc "(Right before I head home, I spot something in the bushes outside the building. It's…)"
    mc "(A folded $50 bill, caught on the leaves.)"
    mc "(It looks like it's my lucky day and someone else's unlucky day. I wonder who could've lost this?)"
    mc "(I look around, trying to spot anyone who could be the owner of this bill. No one's around. The closest person is all the way across the street and they're closer to the bush.)"
    mc "(It's in such an odd position too. I doubt anyone could unintentionally leave a $50 bill on the bushes unless they got tackled into them. Yeah, someone probably felt generous today and left some money for a stranger. My heart goes out to the kind individual who did such a selfless act.)"
    mc "(I snatch the bill away from the branches and put it into my pocket. I should be able to buy food now.)"
    mc "(The sky is darkening quickly, so I have to hurry. The closest store should be… that way.)"
    with fade
    mc "(The automatic doors slide open gently, ringing an electronic doorbell throughout the store. The young cashier welcomes me without a hint of life in his voice. I feel bad for him, but he probably only does this part-time.)"
    mc "(There isn't much in the store that I would want to eat. It's mostly frozen food, but there are some instant ramen cups. Most of the frozen food looks average at best, but there are some seemingly good meals among them.)"
    mc "(I grab a couple of ramen cups and some frozen pizza. It should be enough to last me this week. I'll get some candy as well.)"
    mc "(In total, it uses up around half of my money. I'll save the rest for lunch and other expenses.)"
    mc "(After that mini-shopping spree, it's finally time to head back home. The doors slide open and I step outside.)"
    jump day3