label day3:
    mc "(It's significantly darker outside now. I can still see a hint of purple in the sky, but the sun is almost completely set. The streetlights begin to turn on, lighting up the sidewalk.)"
    mc "(It's not a long walk home, but I have to carry my food with me. The bags I have them in are slowly pressing into my hands.)"
    mc "(At last, I am home again. My hands are tired of carrying the bags, so I drop them off on the counter. I sit down in the chair and relax for a bit before I start to make dinner.)"
    mc "(I'll just heat up some of the frozen food. It should be simple enough, right? I just need to follow the instructions on the box and it should be alright.)"
    mc "(I heat up the food and eat it while watching TV.)"
    mc "(After that, I take a shower and put on my pajamas, getting ready for bed. I still have a while before I should probably sleep, so I wash and dry my casual clothes.)"
    mc "(Finally, it's time to sleep again. I've gotten used to my new place, so sleeping is a lot easier now.)"
    mc "(I don't even need to toss and turn anymore.)"
    with fade
    mc "(Yet another day of life. I can't say I'm excited to go to work, but at least it gives me something to do.)"
    mc "(I get out of bed and get ready for the day. I probably shouldn't eat ramen for breakfast, but I'm an adult and I can make decisions for myself. I slurp it down and head for work.)"
    mc "(I arrive at the office building, ready to fill out more paperwork. I wave hello to Sigma, head to the department, and start working.)"
    mc "(It's not even lunch break yet but I'm already bored of working. My focus begins to waver from the identical looking papers and soon enough I'm fully distracted.)" 
    mc "(I can't make any mistakes in the documentation, but I also can't be bothered to do something this boring for hours upon hours. It's probably time for me to take a break.)"
    mc "(I get up from my desk and head over to the break corner. Joe Joe still isn't there, but it might be because I came at a different time."
    menu:
        "I'll get a cup of..."
        "Water":
            mc "(I grab one of the paper cups attached to the water cooler and fill it up slowly. The conical shape makes it easier to stack and fold the cups, but it holds significantly less water.)" 
            mc "(I admire the bubbles rising from the water cooler into the water jug and take a sip of water.)"
            mc "(The water is quite refreshing, but I don’t feel like it’s helping very much. Maybe the coffee would’ve been a better choice.)"
            mc "(I slowly sip the cup while looking around the office. I feel more focused now.)"
        "Coffee":
            mc "(I grab a cup and place it underneath the nozzle. With a press of a button the coffee begins pouring out, filling up the cup with a light whirring noise.)"
            mc "(The coffee smells amazing and I can feel the heat of it through the paper cup. It warms up my fingers, making me feel more energized before I even take a sip.)"
            mc "(The coffee itself is quite nice. It doesn’t taste particularly good, but it does the job.)"
            mc "(I finish the cup, trying to get the last remaining drops of coffee before tossing it away. I feel more energetic now.)"
    mc "(I try to head back to my cubicle when someone bumps into me, knocking me over.)" 
    with vpunch
    "Random Woman" "Sorry!"
    mc "It’s fine."
    mc "(I look up at the woman who knocked me down.)"
    mc "(She’s... a slime.)"
    mc "(Her body seems to be made of a gelatinous material. Some of it is on my clothes where she bumped into me. She looks quite pretty though.)"
    mc "(She seems to have noticed that her slime got on me.)"
    "Slime Woman" "Oh, I’m so sorry about your clothes."
    mc "(She touches her main body to the parts on my clothing. She pulls of some of it, but she leaves a stain in the process.)"
    mc "Thanks."
    mc "(I get up from the ground and dust myself off.)"
    "Slime Woman" "Wait, are you…"
    mc "Have I met you before?"
    mc "(She might be an old friend of mine from before I lost my memories. I can’t say I can remember seeing her though.)"
    "Slime Woman" "Wow, it is you! I haven’t seen you in forever!"
    mc "Haha, yeah. It’s been so long."
    mc "(I have no idea what she’s talking about.)"
    "Slime Woman" "What were you doing all this time? I thought you moved."
    mc "(Do I tell her? I know you should be honest with your friends, but I’m afraid she wouldn’t like it if I told her that I completely forgot about her. I don’t even know her name.)"
    mc "About that…"
    mc "(She looks at me earnestly, waiting for my answer. What should I do?)"
    "Random Guy" "Hey Goopitha, can you take these papers to the front desk for me?"
    mc "(So she’s Goopitha, huh. Makes sense considering she’s a slime.)"
    g "Yeah, just give me a sec."
    g "Sorry, I’ll listen to your story later. I need to run some errands real quick."
    g "Wait, why are you even here? Have you always been working here?"
    mc "(I was hoping she’d leave me alone…)"
    mc "No, I just got hired a few days ago. This is my third day here."
    g "I can show you around then! Or did Sigma already do that?"
    menu:
        "Sigma already gave me a tour":
            jump touralready


        "Show me around":
            jump goopithatour

label touralready:
    mc "Sigma already did that."
    mc "(Her smile flattens ever so slightly. I feel kinda bad for her now. But she quickly bounces back to her energetic self.)"
    g "Oh, that’s fine. Hold on."
    mc "(She looks around to see if her coworker is still around. To her delight, he has already headed off to somewhere else.)"
    g "I’ll just take those papers later. No one has to know…"
    mc "(Her bright smile turns into a cheeky grin as she winks at me. There goes my plans of not talking about my amnesia.)"
    g "So, how have you been lately? I haven’t seen you in ages!"
    mc "I’ve been good. Not really much happening in my life. What about you?"
    mc "(I hope that I can divert the attention onto her. She seems like the type of person who can’t stop talking once she starts.)"
    g "Oh, you won’t believe what’s happened lately. So, y’know how I’m a slime right?"
    mc "Mhm."
    g "There was this lady…"
    mc "(It looks like I was right on the money. I manage to reach the department before she comes close to stopping.)"
    mc "(She doesn’t really notice that I’m not really responding to her. A few \"mhm\"s and nods are enough to satisfy her. Her story seems interesting, but I don’t really know her well enough to properly respond.)"
    mc "(As I approach my cubicle, I notice something different. Someone is sitting down at my spot. Maybe I just saw something wrong, or perhaps I’m looking in the wrong place. I rub my eyes and try to look again.)"
    g "Did you not sleep well? That’s not good for you, y’know. A normal adult should sleep 7 hours a day."
    mc "No, it’s just…"
    mc "I think someone’s in my cubicle."
    mc "(I point it over to the woman at my desk. I can tell what type of person she is from the way she sits. Her legs are kicked up on the desk and she leans back so far that I’m scared she’ll fall over.)"
    mc "(A black baseball bat is placed on her lap. It almost falls out of her lap as she yawns, but she miraculously grabs it with her free hand.)"
    g "Oh, that’s Pelota! You totally need to meet her!"
    mc "(She happily slides over to Pelota and hugs her from the back.)"
    g "Pelotaaaa!"
    p "Gah!"
    mc "(Pelota twitches in surprise and falls backwards into Goopitha’s slime body. The chair falls straight through Goopitha, but Pelota is suspended in the slime and brought back up to her feet.)"
    p "What do you want?"
    mc "(She hasn’t noticed me at all. Her casual tone makes me think that this is a regular occurrence.)"
    g "Well…"
    mc "(Goopitha reaches over to me and pushes me towards Pelota.)"
    g "This is [name], my old friend! I haven’t seen them in ages!"
    g "[name], this is Pelota. I met her while working here, and I think she’s also quite new to the job!"
    mc "Nice to meet you, Pelota."
    mc "(I reach out my hand. Isn’t Pelota Spanish for-)"
    p "Yo. Nice to meet you too, I guess."
    mc "(She looks into my eyes with a terrifying stare that pierce through my thoughts. She notices my sudden awareness of her name.)"
    p "My name’s shitty. I know. I trust that you understand that, yeah?"
    mc "(She grasps my hand like a vice, squeezing my fingers together.)"
    g "So, what do you do here, [name]?"
    mc "I’m a Charitable Urgency Manager. I’m supposed to fight the diseases and stuff, but I have been doing nothing but paperwork for the past three days."
    p "Oh, you too? I’ve been waiting for another one to show up."
    p "Work is nothing but a pain in the ass, so I just stopped coming here."
    p "So, what’d you do to get stuck with this job?"
    mc "Huh?"
    p "Everyone who gets this job usually gets assigned it by some rich dumbass. I haven’t seen anyone do this voluntarily."
    mc "Why not?"
    p "Cause it sucks ass. If you aren’t wasting your life away doing paperwork, you’re fighting some random disease that’s either a walk in the park or strong enough to burn a hole through your head with a touch."
    p "I’m only here cause I beat the last C.U.M. out of commision and had to cover for him as a payment."
    p "But you don’t seem like the type to beat some dude up. What’s your story?"
    mc "Well…"
    mc "(If only Goopitha wasn’t here, then I could just tell the truth to her. Pelota’s thousand mile stare looks like she wouldn’t believe me if I lied, but what other choice do I have?)"
    mc "I…"
    p "Nevermind. I’m sure you don’t wanna talk."
    mc "(Huh?)"
    mc "(She picks up her bat from the floor and tosses it into the air.)"
    p "Whatever. Actions speak louder than words, right? Tell me your story through your fists."
    g "Guys, don’t fight. We can settle this peacefully."
    mc "(She assumes a fighting pose while motioning me to do the same.)"
    mc "Wai-"
    mc "(Her bat hits the floor. She swings her left leg into my shins. She’s not gonna wait.)"

    # minigame here, for now filler with manual win/lose selection 

    menu:
        "Win":
            mc "*cough* (My body hurts. She really didn't pull her punches.)"
            p "Not bad. I didn't expect that much out of you, but you don't suck as much as I thought you would."
            mc "(She steps on the handle of her bat, launching it into her hand.)"
            p "Here. Drink up. You deserve it."
            mc "(She hands me a bottle of water. My hands can barely move though, so she opens the cap for me.)"
        "Lose":
            mc "*pant* (That really hurt. I think she broke my shoulders or something. I can’t move my right arm.)"
            mc "(I collapse on the ground as my body aches and pulses. It's not a good feeling.)"
            p "You did well. Not to my expectations, but no one's met those before."
            mc "(She tosses a bottle of water onto my body.)"
            mc "(I grab the bottle, but my hands can't muster the strength to uncap it.)"
            mc "(Pelota grabs the bottle from me and removes the cap)."
    p "No problem."
    mc "(I take a sip from the bottle. The water from the bottle tastes different from the one in the cooler. That’s not a bad thing, but it does make me feel weird. It’s almost sweet even though it’s just water.)"
    mc "(After a few more minutes of resting I get up from the floor.)"
    mc "(Pelota is still sitting at my cubicle, but I can probably get her to move. She’s downing an entire bottle of water. It’s really impressive since I don’t think she stopped to breathe at all.)"
    p "Hah."
    mc "(Pelota caps the bottle and tosses it into the waste bin. It almost lands perfectly until Goopitha grabs it out of the bin and bonks Pelota over the head.)"
    g "Don’t do that, Pelota. No one likes getting beat up on their first meeting. You’re gonna scare [name] off."
    p "Gah, I forgot you were here."
    mc "(To be honest, I did too.)"
    g "Apologize to [name]."
    mc "(Goopitha continues to bonk Pelota over the head with the water bottle.)"
    p "Alright, alright. I get it."
    p "My bad. Sorry about that. I like to test everyone that I meet."
    mc "It’s fine."
    mc "(Goopitha looks satisfied and drops the bottle into the waste bin.)"
    g "Right, as I was saying, this is-"
    "Coworker" "Yo Goopitha, have you delivered those papers yet?"
    g "I’m on it!"
    g "Sorry guys, I’ll have to talk to you later. Be nice to each other!"
    mc "(Goopitha heads back to her department, leaving Pelota and I with an awkward silence to fill.)"
    mc "So… how was your day?"
    p "It’s not even lunch break yet and you’re asking me how my day was?"
    mc "...Yeah."
    p "..."
    p "It was fine."
    mc "Mhm."
    mc "(I decide to get back to work. Pelota’s still at my desk, but the cubicles near us are empty. I move my papers over and start to fill out the forms.)"
    with fade


    
label goopithatour:
    mc "You can show me around."
    g "Perfect! Just follow me."
    mc "(She grabs my hand and pulls me towards the main lobby.)"
    g "Okay, so here is the main lobby! I’m sure you’ve already seen this before."
    g "Hey Sigma!"
    mc "(She waves over at Sigma, who glances up from her computer. She looks at us questioningly, no doubt because we’re supposed to be working.)"
    mc "(I wave at Sigma too and smile as she silently stares at me.)"
    g "This way!"
    mc "(Goopitha pulls me with her. We reach the junction where I would normally turn left, but Goopitha drags me to the right. After a few more twists and turns, she finally stops at a department I don’t recognize.)"
    g "This is where I work! Pretty neat, huh?"
    mc "(Her cubicle looks identical to mine, save for the lack of a chair. I guess she doesn’t need to sit down since she’s a slime.)"
    mc "What do you do here?"
    g "I just fill out paperwork. It’s not very interesting, but I get to meet a bunch of cool people. Plus, the pay is pretty decent."
    g "Here, lemme show you what I have to do."
    mc "No it’s fine, I know wha-"
    g "Here!"
    mc "(Goopitha steals a chair from the cubicle next to hers and sits me down in it. She scrambles around her desk, looking for any paperwork that she can show me.)"
    g "Where is it, where is it?"
    mc "(I don’t think she’s noticed, but she’s slowly covering my body with her slime. It’s not the most comfortable feeling. My clothes are sticking to each other and my back is cold.)"
    g "Aha! Here, look at this."
    mc "(Her voice comes from above as she pulls out an empty form. I instinctively look upwards.)"
    mc "(Woah, she’s close! Her entire body is looming over me as she explains how she does her job. I quickly look back down before she notices that I’m not paying attention.)"
    g "Right, so normally you would have a file on someone and…"
    mc "(She continues to explain. It’s not the most interesting speech since my work also needs me to fill out paperwork, but Goopitha acts like it’s the most entertaining thing she’s done.)"
    mc "(She begins to talk about the back of the sheet when I feel a heavy weight on my shoulders. It presses against my back, squeezing me downwards. Are those her-)"
    "Coworker" "Goopitha, did you deliver those papers yet?"
    mc "(I can feel my face flush with red. I hope that guy can’t see the predicament I’m in. That would be beyond embarrassing. I’m afraid to look up, since Goopitha’s body is so close to mine. She might notice that her breasts- or what I hope are her breasts- Actually, why am I hoping that it’s her breasts? Does she even know that they are pressing against me? Her unspecified body part, but preferably-)"
    g "I’m working on it, hold on."
    mc "(Goopitha suddenly moves, scaring me out of my trance. I quickly look up. Unfortunately, or maybe fortunately, it’s just her slime on me. I guess it technically counts as breasts, since they’re in that general area, but that means that any part of her body would also count. I feel my face going even more red when I realize that I hoped that they were her breasts. I hope no one here is a mindreader, however unlikely that would be.)"
    "Random Guy" "Hurry up."
    g "*sigh* Sorry about that. I still need to do a bunch of stuff. But anyways, where were we?"
    mc "(Goopitha’s body slowly creeps forward as she tries to find her place on the paper again. I try my hardest not to move even a millimeter.)"
    g "Oh right. Yeah, from here you would…"
    mc "(Goopitha slowly tightens her slime around me. Maybe it’s instinctual, maybe it’s habitual. Either way, I doubt that she’s doing it on purpose. I mean, is this normal? Maybe she just does this to everyone she meets, and I’m just getting worked up over nothing.)"
    mc "(The slime is quite cold, but over time my body heat warms it up. It’s gotten surprisingly warm now.)"
    mc "(I start to relax my movements when I suddenly start to feel weightless.)"
    mc "Aah!"
    mc "(I accidentally spoke from my surprise. Goopitha’s body twitches and I land back in my seat.)"
    g "What’s wrong, [name]? Did you-"
    mc "(Goopitha looks down at me. I freeze in fear, hoping she wouldn’t find what happened weird. I mean, she did this herself, right? Surely I’m not at fault, right?)"
    g "Ah."
    mc "(Her face instantly turns a bright red. She covers her face with her hands.)"
