label intro:
    scene bg konbini
    with fade
    mc "(This one's $2.99 and it's 1 cup, but this one's $4.50 and 1.5 cups. I think they're the same in terms of cost, but which one would taste better?)"
    mc "(Screw it, I'll get the $2.99 one. They'll probably taste the same, right.)"
    mc "(I walk to the cashier and check out my items. Nothing besides my cup of ramen and a few pieces of bright, colorful candy.)"
    "Cashier" "Thank you for shopping with us."
    scene bg nightalley
    with fade
    mc "(As I step outside, a cool, yet gentle breeze brushes by my face.)"
    mc "Another cold night, huh."
    mc "(The breeze that wisped by me carries my sight upwards, into the star-lit sky.)"
    mc "(The glitters of millions of stars inconceivably far away fill my eyes. The beautiful streaks of purple and orange slice through the monotonous, grey backdrop of the darkened atmosphere.)"
    mc "(It hasn't been so dark yet so early in a while. I'll need to start carrying my winter clothes with me now.)"
    mc "(Suddenly, the rumbling of a car's engine knocks me out of my trance.)"
    mc "(I should head home now.)"
    mc "(A small, but brightly colored bar interrupts my calm walk home. Its neon colors flash throughout the street, making me feel nostalgic.)"
    mc "(I miss the days of neon lighting and cheery nightlife. Something about the cool colors and rounded shapes and signs reminds me of a simpler time.)"
    mc "(As I swing my grocery bag around needlessly, a small group of people burst out of the bar, laughing and shouting and all.)"
    mc "(So much for my calm walk back. I'd rather not be around random drunks, so I'll hurry up.)"
    mc "(They also start walking, heading in the same direction as I am.)"
    "Drunk Guy" "Nah, I'd clobber you in a second, mate. Don't even try to start that."
    "Other Drunk Guy" "Bet."
    mc "(I don't like this. Please, just slow down or something so I don't have to deal with you.)"
    mc "(I speed up my walking to not get involved.)"
    mc "(There are a lot of dangerous people here. I don't think I should come here again, at least not at night.)"
    "Drunk Guy" "Watch this."
    scene black 
    with fade 

    mc "(It's really quite something, losing all of your memories.)"
    mc "(My family, my friends, my identity. All gone in a matter of seconds.)"
    mc "(I still know how to do basic actions and what happened right before the accident.)"
    mc "(I know that someone hit me with a brick, but apparently I stumbled onto the street as well, just as a car drove by.)"
    mc "(The doctors told me it was permanent. Something about severe brain trauma, and how it was a miracle I can still live now.)"
    mc "(Oddly enough, I don't really feel sad or angry about it. I don't really feel anything right now. I mean, am I supposed to feel something? I just lost everything, right? Surely I should feel something, right?)"
    mc "(But nothing comes to me. I don't know how I should react. I don't know what the old me would have done. I can only stay silent, waiting for something to happen.)"
    mc "('A miracle I can still live', huh. I certainly don't feel alive right now. I don't have the emotions that a normal person would have. Emotionally speaking, I'm on the same level as a corpse.)"
    mc "(At least I'm still here, right.)"
    scene bg hospital
    with fade 
    mc "(It takes some time for me to recover. My body isn't as badly injured as it appeared to be, but it still took some time. About two months, actually."
    mc "Soon enough I'll be able to walk again, and after that I could go back to how I used to be, minus the memories. I tried my best to feel something in my heart."
    mc "Books that would inspire even the most hopeless of individuals would only make me more willing to turn around in bed. Movies that would turn stoics into sobbing messes can force less tears out of my eyes than a yawn.)"
    mc "(But at least I'm willing to feel something.)"
    with fade
    mc "(A few weeks after that, the doctors allowed me to walk. I could get up and move around the room and the halls, as long as an attendant was with me.)"
    mc "(I barely moved from my bed at all. I didn't see a need, since I didn't have anything to do once I stood up. If I needed to use a bathroom, it only took a few seconds to get there. I didn't need to walk around for a few minutes.)"
    mc "(Something strange happened after this checkpoint in my recovery. My back started tingling, my legs started getting sore. But most importantly of all, my head started to ache."
    mc "It was like my brain had expanded 3 sizes, but my skull didn't catch up. I felt an odd pressure against the front and back of my head.)"
    mc "(No matter what I tried, I couldn't get it to stop. It was such a minor pain that I didn't want to bother the doctors, but it was getting so bad that I couldn't stand it anymore.)"
    mc "(I'll just call the nurse.)"
    mc "(I press the red button on my nightstand. A dull electric buzz sounds throughout the room.)"
    mc "(The nurse hasn't come yet. I don't know how long I've been waiting, but it seems like an eternity. I press the button again.)"
    mc "(It's stuck. The button is stuck in the pressed state, and even though it goes down slightly when I press it, I don't hear a buzz.)"
    mc "(...)"
    mc "(Is there any way I can call the nurse from here?)"
    mc "(I look around the room, trying to find something that can help. But I don't see anything.)"
    mc "(Looks like I'll have to get up. I don't want to do that.)"
    mc "(I get up from my lying position and sit up on the bed. A huge wave of dizziness washes through my head and I almost fall back down.)"
    mc "(I can't tell if I'm moving or not, but I manage to keep my ground and wait for the dizziness to settle.)"
    mc "(I try to twist over to the side of the bed, but I don't know if it's the muscle loss from the coma or simply my body refusing, but I can't move. My elbows lock up and my muscles start twitching rapidly.)"
    mc "(Do I really need to get up? Surely I can just wait for the routine check-in that the nurse does?)"
    mc "(I begin to relax my body. I start to pull the covers back over my body. Their warmth comforts me, yearning for my return.)" 
    mc "(It feels so calming, that in this world of uncertainty, there is at least something that will accept me.)"
    mc "(But my head twinges in pain. My brain begins to contract and twist in my skull. It's so painful that I can't give up. Leaving it would be akin to torture.)"
    mc "(I force my body to get up from the bed. My arms cry out, but their pain is nothing compared to the ache that my head feels.)"
    mc "(I've gotten up from the bed. There's only one step left. I need to stand up and walk over to the nurse's office. My vision starts to sway and the dizziness returns. A TV-like static shocks my eyes.)"
    mc "(I can't tell if I need to move my legs up or down. I don't know if I can handle the pain any longer. I need to act now.)"
    mc "(I feel something inside my legs. Something primordial, something instinctual, something that if I forgot I would be so dearly regretful.)"
    mc "(I trust that feeling. I don't have anything else to go on. Not now, at least.)"
    mc "(My legs straighten up, forcing my torso up with it. My headache is unbearable. I'm going to collapse.)"
    mc "(But it stops. No pain, no static, no dizziness. It's gone in a matter of seconds. Almost like it never was there to begin with.)"
    mc "(My vision clears up. My arms relax. My brain is calm.)"
    mc "(I'm up.)"
    mc "(I've gotten a lot better at fine motor movements.)"
    mc "(I used to not even be able to pick up a pencil. Now, I can peel apples with my eyes closed.)"
    mc "(My other functions have improved as well, and as such, they moved me out of the ICU and into a regular hospital room.)"
    mc "(I'm quite sure I've made a full recovery, besides my memories, but the doctors want to keep me here until all of their concerns are gone.)"
    mc "(Now that I think about it, what am I going to do after I'm discharged?)"
    mc "(The nurse told me I was a college student before I got injured, but I don't think I can go back after missing so many classes.)"
    mc "(I'm still young, so I can't retire and spend the rest of my days in solitude.)"
    mc "(Hmmm…)"
    "*knock knock*"
    mc "(The nurse is here for his mid-day visit…)"
    "The door opens..."
    "Nurse" "Good afternoon!"
    mc "Hello."
    "Nurse" "How are you feeling today?"
    mc "Fine."
    "Nurse" "That's good."
    "Nurse" "Oh! You're being discharged today."
    mc "Really?"
    "Nurse" "Mmm. See, the thing is you don't have a home to go back to…"
    mc "(What?)"
    "Nurse" "And you also don't have the money to pay for the medical bills…"
    mc "(WHAT?)"
    mc "(He hands me a stapled list of papers containing all the expenses of my recovery.)"
    mc "(My eyes nearly water in disbelief. I hear my soul making a deafening shattering sound as I tally up the total.)"
    mc "Almost half a million…"
    mc "(This can't be real. Surely not?)"
    mc "(Unfortunately it is. Printed right at the bottom is a six-digit number: $457,860.65. Ambulance, medical supplies, surgeries, all merge forces to put me $458k in debt.)"
    "Nurse" "Yeah, it's a pretty impressive bill."
    "Nurse" "Fortunately for you, a kind man was willing to pay it off for you. However, he only did so on the condition that he could have a conversation with you before you left the hospital."
    mc "(Those words put a halt to my despairing mood in its tracks.)"
    mc "(All of it? What kind of millionaire is this guy? Why would he pay off some random person's medical bills?)"
    mc "(I don't think I'll be able to thank him properly, but if all he wants is a talk then I'll gladly respond.)"
    mc "I'll talk to him. Where do I meet him?"
    "Nurse" "Oh, he'll come in here shortly. In the meanwhile, you should probably prepare to leave soon."
    mc "(Prepare to leave? Didn't she say I don't have a home to go back to?)"
    mc "(But before I can ask, the nurse closes the door behind her and I'm once again left alone in the room. It doesn't help with the fact that hospital walls are so depressing.)"
    mc "(As I gather my thoughts, I look around the room for anything I'd like to take with me.)"
    mc "(Again, hospitals like to save money due to the expensive equipment. None of it is anything I can keep. I did borrow a few books from the library they have here, but only patients have the right to borrow them.)"
    mc "(Maybe I could ask for some of the coloring materials they give the children? They get used up every few weeks, so it's not like they're completely permanent. I don't need half-used crayons and colored pencils though, so I'd rather not do that.)"
    mc "(Before I can make a conclusive decision on what to steal from the hospital, the door swings open without so much as a knock.)"
    mc "(What a gentleman. Actually, I'm pretty sure this is the person who wanted to talk to me, so I shouldn't judge them before I get to know them.)"
    mc "(When I turn my head towards the door to try to greet my unknown savior, a powerful blast of cologne smacks into my face in the same manner as their door etiquette.)"
    mc "(This guy...)"
    mc "(As I recover from my involuntary trip down the Men's Beauty aisle, the loud clicking of dress shoes calmly approaches.)"
    mc "(A tall man steps through the door. He's dressed formally, with a matching black suit and pants, a pure white dress shirt, and a charcoal-colored tie that makes up the look of business formal.)"
    mc "(While some may call it professional, to me it just looks plain.)"
    mc "(That opinion doesn't apply when I get a good look at his face, however.)"
    mc "(Damn, he looks fine!)"
    mc "(This guy's got everything hasn't he, good looks, lots of money…)"
    mc "(Not that much now that I think about it. I shouldn't be too jealous of my mysterious hero.)"
    "He smirks"
    "Cool Man" "What, did I kick down the door too hard? Your eyes are blinking like a broken light."
    mc "(I quickly try to reassemble my expression into something worthy of conversation.)"
    mc "Sorry, you just surprised me."
    "Cool Man" "No worries. That happens to everyone on the first meeting."
    mc "(He steps closer to the bed and leans toward me.)"
    "Cool Man" "Hmm…"
    mc "(He's way too far into my personal space. I can feel his breath on my face.)"
    mc "Um, can I help you?"
    mc "(He seems to have realized how close he was.)"
    "Cool Man" "My bad, that's a bad habit of mine."
    mc "(Not bad enough to make him back off from me though.)"
    mc "(He continues to analyze me like a shark circling its prey. His aggressive eyes stare me down, missing not even a single hair on my body.)"
    mc "(Every fold of my skin, every pattern in my movements, every slight twitch of a muscle. Nothing seems to escape his sight.)"
    mc "(Finally, he leans back up and pats me on the head.)"
    "Cool Man" "Better than I expected. Certainly worth half a million."
    "Cool Man" "I'm sure you're quite confused right now. Don't worry. It'll all make sense soon."
    "Cool Man" "I work for a certain section of the government called the Disease Eradication Unit. As the name suggests, our job includes the extermination of diseases and the various cleanups relating to them."
    "Cool Man" "But dealing with diseases is a difficult job. People go missing, die, get PTSD, and worse. We have trouble finding backup employees should any one of these tragedies happen to one of our main employees."
    "Cool Man" "That's where you come in. You don't have a home to return to, or family and friends to care for if you go missing. I won't sugarcoat this. You will be a disposable pawn to the higher-ups."
    "Cool Man" "You'll do most of the work, but get the least of the benefits. It's not a very good position to be in."
    "Cool Man" "But don't worry. The benefits you will get are pretty good if I do say so myself."
    "Cool Man" "You get a free apartment, with gas and water all paid for. You get a pretty decent paycheck, and also the experience of a proper work environment with lots of friendly co-workers."
    "Cool Man" "What do you say?"

    menu:
        "Yes":
            jump coolguyyes
        "No":
            jump coolguyno
label coolguyyes:
    mc "(I'd rather not do this, but I want to thank him for saving my life. Plus, I do need a home to return to if I want to live well."
    mc "I'll join."
    "Cool Man" "Excellent, just as I expected. Pack your things, I'll see you around shortly."
    mc "(He stands up and steps out of the room, his dress shoes clicking with every step.)"
    mc "(As I get up from the bed, I feel slightly uncomfortable.)"
    mc "(I haven't gotten up in a while.)"
    mc "(I'm probably out of shape too.)"
    mc "(I sigh as I gather my clothes in one place.)"
    mc "(But before I can put them into my bag, I feel my vision begin to fade.)"
    mc "(Not again…)"
    with fade
    mc "(My eyelids feel uncomfortably heavy.)"
    mc "(My body feels compressed as if I've shrunk by multiple inches. But I can that I'm on a bed of some sort.)"
    mc "(My eyes feel dry, despite having been covered for as long as I have slept.)"
    mc "(I slowly open my eyes. The room I'm in is foreign, but it looks somewhat homely. The ceiling is such a light brown color that I feel like it's white and my eyes are tricking me.)"
    mc "(I blink a couple of times to try to wet my eyes before giving up as it seems to have no effect.)"
    mc "(I get out of my resting position and look around the room. I'm wearing a light set of pajamas. There's a cup of water on the nightstand, with a small note next to it.)"
    "Nurse" "Good morning, [name], I hope you had a good rest. Your work clothes are in the closet, enjoy your new home."
    mc "…"
    mc "(I get out of bed and walk over to the closet. It's not the largest closet, but it has a mirror next to it so I can check my hair.)"
    mc "(These pajamas are pretty cute, aren't they.)"
    mc "(Wait, these are different from the ones in the hospital.)"
    mc "(Did he…)"
    mc "(Why?)"
    mc "(I decide to not dwell on it for too long, since I doubt he did much more than swap my outer clothes. I sure hope he didn't, anyway.)"
    mc "(Inside the closet is a clean, black and white formal outfit. It's about the most plain yet decorated outfit I've seen.)"
    mc "(I step outside of the bedroom, expecting a hallway, only to encounter the living room.)"
    mc "(Not exactly the largest apartment I've got here.)"
    mc "(But a home is a home. There's a small TV with an armchair in the room, so it's not the worst.)"
    mc "(On the other side of the room is an opening into the kitchen. I can't cook though, so I hope that guy got me some food.)"
    mc "(I open the fridge and look around. Nothing.)"
    mc "(My expectations were low, but I still feel like I've been scammed.)"
    mc "(I sigh and shut the fridge door, hoping that my past self magically remembers how to make breakfast.)"
    mc "(But before I accidentally start a fire in my brand new home, I spot a plate of eggs and a glass of milk. And another note.)"
    mc "Eat up! (There's also an image of a thumbs-up.)"
    mc "(I'm sorry for ever doubting you, cool guy.)"
    mc "(I quickly eat up the eggs and down the milk. It doesn't taste that bad. Who am I kidding, it's the best meal I can remember. Anything beats IV drip.)"
    mc "(I head for the door before I realize that I don't know where work is.)"
    mc "(That isn't that much of a problem though, since that guy probably left another note.)"
    mc "(There isn't one though. He only left the house keys and a map with a small red circle on a building.)"
    mc "(I guess he ran out of time…)"
    mc "(I step out of the door and lock it behind me.)"
    mc "(Now that I'm out of my house, I suddenly don't feel like working anymore.)"
    mc "(I don't want to back out now. Not after I've gotten a free home and breakfast.)"
    mc "(I head down the stairs so I can reach the ground level. It's only 2 sets of stairs. I pity those who live on the upper floors, but at least they'll never skip leg day.)"
    mc "(I look at the apartment keys as I'm descending. 308. Not a bad number. It's an even number, at least.)"
    mc "(The workplace isn't that far from the apartment, so I'll just walk there. I should get some exercise, anyway.)"
    mc "(I haven't been outside in a while. The hospital staff never let me leave the premises since I wasn't fully recovered, but I got to walk around the hallways and look out the windows.)"
    mc "(The only thing I could see was trees, though. Large rectangles of green, occasionally intersected by buildings. They got boring after a while.)"
    mc "(They look much more different up close though.)"
    mc "(They're much bigger than I thought. I guess only seeing something from 10 floors up messes with your perception.)"
    mc "(Who would've guessed that life is much more fun when you're not stuck in a hospital room.)"
    jump day1work

label coolguyno:
    mc "(I'm not gonna place myself in danger just so I can buy a home. No matter how nice that apartment is, it's not worth my life." 
    mc "I refuse."
    mc "(He gives me a strange look like he wasn't expecting that.)"
    mc "Sorry, but I don't want to put myself in danger."
    "Cool Guy" "No matter. Suit yourself."
    mc "(He tosses me a folded map of the city with a red trail, showing the route to the apartment complex from the hospital.)"
    mc "I said I didn't want to join."
    "Cool Guy" "Not like you have a choice, do you? I don't think a broke amnesiac will survive long on their own without a place to call home. Plus, the major players at the DEU want to see their money well spent."
    "Cool Guy" "Room 308. I left a few furnishings so you don't have to sleep on the ground."
    mc "(He places the key on top of the map and leaves. The clicks of his dress shoes echo down the hallway as he leaves the door open.)"
    mc "(I slide out of bed and stack my spare clothes with the map and keys. It's not much, but it's better than only having one set.)"
    mc "(I place them all into a small plastic grocery bag and slide the keys into my pockets.)"
    mc "(As I unfold the map, a small slip of paper falls out. It's a handwritten note, seemingly meant to convey some important information.)"
    mc "(What's this?)"
    "Note" "Report to DEEZ Corp tomorrow for your first day at work. Dress well."
    mc "(That bastard…)"
    mc "(I said I didn't want to join. How pushy can one be?)"
    mc "(I want to get angry at him, but whenever I remember his beautiful face I just can't get mad.)"
    mc "(I decided that the best way to get back at him was to not think about him at all, so that way he doesn't even get to be in my mind.)"
    mc "(Before I step out of the hospital room, I turn around to take a good look at what I called home up until now.)"
    mc "(Now that I see it from here, it looks incredibly plain. The walls and ceiling are a light beige color, while the floor is a strange tiled pattern that connects with the hallway.)"
    mc "(And the white curtains that I rarely move look like they've been taken straight out of a fabric store.)"
    mc "(Strangely enough, I feel nostalgic. This cookie-cutter room that could be put anywhere and still called a \"hospital room\" makes me feel at home.)"
    mc "(Not a single part of it is unique. None of it stands out, and I would confuse it with the room next to mine if they were mixed around.)"
    mc "(But I just can't leave it behind. I've called this place home for years, and now I have to leave it? I don't want that.)"
    mc "(I want to stay in the lands of familiarity, keeping change at bay for the rest of my life.)"
    mc "(But I must move on. I can't stay like this forever.)"
    mc "(I feel weird being so emotional about a hospital room. I'm almost crying about something that most people wouldn't even bat an eyelash at.)"
    mc "(But these emotions are very much real. I can't fault myself for feeling them, can I.)"
    mc "(I finally tear myself away from the door and shut it behind me.)"
    mc "(It's time to move forward.)"
    mc "(I walk towards the elevators, clutching my bag of clothes tightly against my chest.)"
    mc "(It's all I have, after all.)"
    mc "(When I step out of the hospital, a golden ray of sunlight hits me in the eye.)"
    mc "(Damn, that's bright.)"
    mc "(I'm not used to the sunlight. The nurses always kept the curtains shut because it could bother the patients.)"
    mc "(I pull the map out of my pocket and unfold it so I can tell where I should be heading.)"
    mc "(It's quite the walk away. At least my legs will get some well-needed exercise.)"
    mc "(The distance isn't the shortest, but the route itself is pretty simple.)"
    mc "(I study the map one last time before I fold it back up and put it into my pocket.)"
    mc "(The outside world is quite incredible. The trees, the air, the sky. All of it feels refreshing compared to the insides of the hospital.)"
    mc "(Did the previous me get to experience this all the time? Lucky…)"
    mc "(The sounds of cars rushing by me are also quite refreshing. All different makes and models, with a few of them nearly identical save for the color. They make a nice sound, speeding by at such speeds that they appear as a blur to me.)"
    with fade
    mc "(By the time the building comes into view, the sky has already become a melancholy mix of pink and gold.)"
    mc "(The apartment complex looks pretty simple. A medium-sized parking lot right in front of a tall, 5-story building of apartment after apartment.)"
    mc "(As I'm about to walk up the stairs, a young man rushes down the stairs, bumping into my shoulder.)"
    show joejoe
    "Young Man" "My bad."
    mc "Sorry."
    hide joejoe
    mc "(He rushes off before I can get a good look at his face.)"
    mc "(That guy seems like he's in a hurry. I wonder what he's up to.)"
    mc "(I climb up the rest of the stairs with no interruptions and reach the third floor.)"
    mc "(Room 308, room 308.)"
    mc "(Right here.)"
    mc "(The lock clicks open and the door swings back with a slight squeak.)"
    mc "(Not bad.)"
    mc "(The first thing I notice is the light aroma of mint, pouring out of a small wall-connected air freshener. It instantly gives me the impression that the apartment is cleaner, despite doing nothing to the actual appearance of it.)"
    mc "(The main room has a small TV with an armchair, along with an empty bookshelf.)"
    mc "(There's an opening to the kitchen and another to the bedroom.)"
    mc "(I head to the bedroom first to put away my clothes.)"
    mc "(The closet is nearly empty, besides a few clothing hangers and a set of business clothes off to the side.)"
    mc "(He was serious about me going to work…)"
    mc "(I put my clothes on the hangers and put them all into the closet.)"
    mc "(I'd like to check out the kitchen, but honestly I'm too tired. I'll clock out for the day right now.)"
    mc "(I toss my current clothes into the laundry hamper and put on my pajamas before I slide into bed.)"
    mc "(While I'm here, I should get a general map of the whole apartment in my head. I doubt it'll help with anything, but it makes me feel like I've been here longer than I have.)"
    mc "(My mind wanders around the countless thoughts that have come to fruition, from the cool man to the streets outside. After a while, I sifted out the meaningless ones and presented the major events to the imaginary court inside of my head.)"
    mc "(First, I now have a home and a job. That solves my two major issues. What do I even do for my job though? I don't think that guy left any instructions for me. I can't even work, then.)"
    mc "(I don't think that matters though since everyone around me will lower their expectations accordingly. No matter how well I do it'll always be as expected.)"
    mc "(There is more on my mind than just that, but I don't care enough to handle that.)"
    mc "(I can't sleep, though. I open up my eyes as if that might help. Maybe it'd reset my sleep, or make me more tired so I can rest.)"
    mc "(Right above me is the same darkened ceiling that I've seen every night in the hospital. With the light off, it's hard to tell where the ceiling ends and the walls begin, but it's easier when I look directly upwards.)"
    mc "(It doesn't matter if my eyes are closed or open, it's still just as dark. But I close my eyes anyway, and lean to the side.)"
    mc "(I slowly drift off into sleep…)"
    with fade
    mc "(My mind feels hazy like I haven't fully woken up yet. I can tell that I'm at least somewhat awake, but I don't want to move.)"
    mc "(I lie in bed for another 10 minutes before I feel like I've fully woken up.)"
    mc "(Now that my mind is clear, I can think about what I want to do for the day.)"
    mc "(I might as well head to work. I don't have anything else to do.)"
    mc "(Even though I don't want to.)"
    mc "(I get out of bed and run my fingers through my hair, brushing it away from my eyes.)"
    mc "(I stretch out my arms as far as they are willing to go before doing the same to my legs.)"
    mc "(Finally, I exhale deeply and open up my closet to get dressed.)"
    mc "(I put on my business clothes and head to the kitchen for breakfast. There's a plate of scrambled eggs and a glass of milk on the counter. I guess the cool guy made it for me.)"
    mc "(It tastes pretty good. I'd be fine eating this every day, but it'd probably get boring soon enough. I finish the plate in just a few minutes. It's time to head to work now.)"
    mc "(I head out the door and lock it behind me, before going down the stairs to the ground level.)"
    mc "(As I look at the map again, it doesn't seem that far. I should be able to just walk there.)"
    with fade
    jump day1work

            
